-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 11, 2023 at 09:36 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rentalgoods`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_user_info`
--

CREATE TABLE `admin_user_info` (
  `sno` int(8) NOT NULL,
  `user_name` varchar(20) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `date_of_birth` varchar(10) NOT NULL,
  `aadhar_card_no` bigint(15) NOT NULL,
  `address` varchar(255) NOT NULL,
  `city` varchar(20) NOT NULL,
  `country` varchar(20) NOT NULL,
  `postcode` int(10) NOT NULL,
  `mobile_no` bigint(15) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin_user_info`
--

INSERT INTO `admin_user_info` (`sno`, `user_name`, `gender`, `date_of_birth`, `aadhar_card_no`, `address`, `city`, `country`, `postcode`, `mobile_no`, `email`, `password`, `timestamp`) VALUES
(2, 'Admin', 'male', '20/03/2001', 849562316412, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, porro. Nobis labore ad atque asperiores magnam illum natus sequi inventore voluptas maiores voluptatibus dolorem non exercitationem, ratione reprehenderit ab odit.', 'lknlio', 'lknlni', 94616, 614974913, 'admin@gmail.com', '$2y$10$wud5wJP.e1iGOtu/wk2J4u1Ee4dEPmiQxFYTYN4dZbrMJAfdVhHQu', '2023-05-03 19:51:23'),
(3, 'Mukesh Suthar', 'Open this ', '01/02/2001', 1499, '232, surbhi vihar society', 'surat', 'gujarat', 395010, 7917929791, 'mukesh@gmail.com', '$2y$10$mMFPAnz/xXjH33u8rfgFBuf4o86Hy5e8OuCPnPquwPF3/dDnXXwtW', '2023-06-17 17:30:07');

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `sno.` int(8) NOT NULL,
  `category_name` varchar(30) NOT NULL,
  `item_contains` int(8) NOT NULL,
  `admin_id` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`sno.`, `category_name`, `item_contains`, `admin_id`) VALUES
(15, 'washing machine', 4, 0),
(20, 'tv', 0, 0),
(21, 'freeze', 0, 0),
(22, 'freeze', 0, 0),
(23, 'washing machine', 4, 2),
(27, 'chair', 1, 2),
(29, 'table', 0, 2),
(30, 'sofa set', 1, 2);

-- --------------------------------------------------------

--
-- Table structure for table `contactus`
--

CREATE TABLE `contactus` (
  `sno` int(8) NOT NULL,
  `user_name` varchar(20) NOT NULL,
  `user_email` varchar(30) NOT NULL,
  `subject` varchar(100) NOT NULL,
  `message` text NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `contactus`
--

INSERT INTO `contactus` (`sno`, `user_name`, `user_email`, `subject`, `message`, `timestamp`) VALUES
(1, 'nikhil', 'nikhil123@gmail.com', 'none', 'this is a message.', '2023-06-03 10:16:07');

-- --------------------------------------------------------

--
-- Table structure for table `customers`
--

CREATE TABLE `customers` (
  `sno` int(8) NOT NULL,
  `admin_id` int(8) NOT NULL,
  `customer_name` varchar(30) NOT NULL,
  `customer_email` varchar(50) NOT NULL,
  `contact_no` bigint(15) NOT NULL,
  `joining_date_time` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `customers`
--

INSERT INTO `customers` (`sno`, `admin_id`, `customer_name`, `customer_email`, `contact_no`, `joining_date_time`) VALUES
(1, 2, 'ravi', 'ravi@gmail.com', 6281953468, '2023-05-05 19:52:08'),
(2, 2, 'sunny sigh', 'sunny002@gamil.com', 9481632502, '2023-05-05 19:53:30'),
(3, 1, 'nikhil khairnar', 'nikhil@gmail.com', 9461587320, '2023-05-05 19:54:24'),
(4, 2, 'jayshree patil', 'jayshree@gmail.com', 8461957320, '2023-05-05 19:59:43'),
(5, 2, 'dixit rajpurohit', 'dixit025@gmail.com', 8495316782, '2023-05-05 20:02:26'),
(6, 2, 'mukesh suthar', 'mukesh910@gmail.com', 9461325064, '2023-05-05 20:03:11');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(8) NOT NULL,
  `admin_id` int(10) NOT NULL,
  `title` varchar(150) NOT NULL,
  `brandname` varchar(20) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `rent` decimal(10,2) NOT NULL,
  `category` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `admin_id`, `title`, `brandname`, `description`, `image`, `rent`, `category`) VALUES
(7, 2, 'Amazon Basics Steel Zero Gravity Reclining Lounge Portable Chair, Black ', 'Amazon Basics', 'Zero-gravity outdoor chair provides a stress-free weightless feel for optimal relaxation;Powder-coated steel frame for strength and lightweight portability. \r\nDouble bungee support system securely connects the weather-resistant Textilene fabric to the frame;Weather-resistant Textilene fabric stands up to outdoor elements, offers comfortable breathability, and doesn’t retain heat. \r\n90 kg weight capacity; padded headrest and gently contoured arm rests;Weighing just 7.5 Kg, the portable zero-gravity chair can be transported easily from one location to another. \r\nMeasures 43.3 x 25.5 x 35.5 inches (LxWxH);1 year limited warranty.  \r\nSeat Material Type: Mesh; Assembly Instructions: Require Assembly; Material Type: Alloy Steel; Warranty Description: 1 Year Warranty On Manufacturing Defect; Frame Material Type: Alloy Steel; Item Type Name: Recliners; Back Style: High Back; Is Assembly Required: True; Size Name: Standard; Form Factor: Recliner. ', '6459dfc3a925c.jpg', '55.00', 'chair'),
(8, 2, 'LG 8 Kg 5 Star Inverter Touch panel Fully-Automatic Front Load Washing Machine with In-Built Heater', 'LG', 'Fully-automatic front load washing machine: Best Wash Quality, Energy and Water efficient. \r\nCapacity 8 kg: Suitable for large families. \r\nEnergy Rating 5 Star: Best in class efficiency. \r\nManufacturer Warranty: 2 years on product, 10 years on motor (T&C). \r\n1400 RPM: higher spin speeds helps in faster drying. \r\n10 washing programs: Cotton, Cotton Large, Mix, Easy Care, Baby Care, Sports Wear, Delicate, Wool, Quick 30, Rinse+Spin, Steam Cycle. \r\nLG Inverter Direct Drive Technology- The drum and motor are connected directly which leads to less noise & vibration and, more durability. \r\nKey Features: 6 Motion DD technology provides optimized motion combinations for each fabric type, Hygiene Steam Wash, Tub Clean, Smart Diagnosis System: fast and easy way to troubleshoot issues, Touch Panel. \r\nSpecial Features: Temperature Range - Cold/20/30/40/60/95ᵒC, Remaining Time Delay, Remaining Time Display, Fuzzy Logic, Child Lock , Crease Care, Shock Proof, Silent operation. \r\nIncluded In The Box: 1 unit of Washing machine, 1 Unit of Inlet Hose, 1 Unit of Spanner, 1 Unit Owner\'s Manual. \r\n', '6459ebe2e87b7.jpg', '200.00', 'washing machine'),
(9, 2, 'Godrej 7 Kg 5 Star Fully-Automatic Top Loading Washing Machine', 'Godrej ', '7 Kg Fully-automatic top load washing machine: Affordable with great wash quality, Easy to use. \r\n5 Star Energy Rated Model : Best in class efficiency. \r\nManufacturer warranty: 10 Year Warranty on Wash Motor and 2 year Warranty on product. \r\n700 Spin RPM: higher spin speeds helps in faster drying. \r\n5 Wash Programs: Strong , Auto , Rinse only , Spin only , Rinse + Spin. \r\nMade in India. \r\nI-wash Technology: Calculates, Soaks washes and Dries at the press of a button. \r\nDrum / Pulsator type & Body material: Plastic Drum/Turbo 6 Pulsator. \r\nTurbo 6 Pulsator: 6 ridges that create water motions inside the tub for better penetration of detergent and easy dirt removal. ', '6459f91803da5.jpg', '180.00', 'washing machine'),
(11, 2, 'Haier HWM70-AE 7Kg Top Loading Washing Machine ', 'Haier ', 'Haier fully-automatic top load washing machine: Affordable with great wash quality, easy to use. \r\nCapacity 7 kg: Suitable for small families. \r\nManufacturer warranty: 2 years on product, 10 years on motor. \r\n801 Spin RPM: Higher spin speeds help in faster drying. \r\nWash programs: 8 wash programs, provides easy control buttons for a complete wash program.\r\nComes with Child Lock feature for supreme safety features. \r\nMagic Filter: To capture all the lint. \r\nCleans heavy and large clothes easier with Balance Plate Pulsator, when a load imbalance is detected, the system automatically redistributes the garments evenly, reducing heavy vibrations. \r\n', '6459fc68c6bb2.jpg', '160.00', 'washing machine'),
(12, 2, 'Whirlpool 7.5 kg  5 Star Inverter Fully-Automatic Top Loading Washing Machine with In-Built Heater ', 'Whirlpool ', 'Premium Edge to Edge aesthetic with 12 Wash Programs - Daily, Heavy, Delicates, Whites, Stainwash, Anti Bacterial, Eco, Woollens, Bed Sheet, Rinse + Spin, Spin, Wash Only. \r\nIn-Built Heater Technology: Can heat water at 3 different levels - Warm, Hot & Allergen free. \r\nIntellisense Inverter Motor: consumes less energy and produces less noise and vibration. \r\n360 Bloomwash Action with Hexabloom Impeller. \r\nHard Water Wash Technology. \r\nLED Digital Display & Soft Close Lid: gives a premium experience and protects the glass lid from any damage. \r\nAuto Tub Clean Feature.', '645a02d19e541.jpg', '230.00', 'washing machine'),
(13, 2, 'Sleepyhead Yolo - 3 Seater Sofa (Fabric, Sesame Grey) ', 'Sleepyhead', 'SEATING CAPACITY: 3 Seater | WARRANTY: 3 Year Manufacturing Warranty | FEATURES : Fixed Tufted Back | Durable | Termite Resistant | High-Density Foam | ASSEMBLY: Required, Fulfilled by Brand with-in 48 Hours from the Date of Delivery for Metros and with-in 4 days from the Date of Delivery for Non-Metros. ', '647ac3b48a49c.jpg', '500.00', 'sofa set'),
(15, 2, 'Samsung 183 L 4 Star Digital Inverter Direct Cool Single Door Refrigerator ', 'Samsung ', '\r\n    Direct Cool Refrigerator : Economical and Stylish Single Door Refrigerators for powerful cooling that can last longer\r\n    Capacity 183 Liters: Suitable For Families With 2 To 3 Members\r\n    Star Rating : 4 Star: High Energy Efficiency\r\n    Digital Inverter Compressor : Enjoy greater energy efficiency, less noise and a long-lasting performance. Consumes 50% less power, backed up by 20 year warranty\r\n    Interior Description : Fresh Food Capacity : 165L | Freezer Capacity : 18L | Total No Of Compartments : 1 | Drawers : 1 EA | Shelves : 2 EA | Shelf Type : Toughened Glass Shelves | Anti-Bacterial Gasket | Bottle Storage Capacity : 5\r\n    More bottle space : With a Deep Door Guard can safely store larger bottles, bulky cartons of milk and juice and more beverage items without wasting space\r\n', '648d9d84f0ecd.jpg', '200.00', 'fridge'),
(16, 2, 'LG 185 L 5 Star Inverter Direct-Cool Single Door Refrigerator ', 'LG', '\r\n    Direct Cool Refrigerator: Economical and stylish\r\n    Capacity 185 liters: Suitable for families with 2 to 3 members/ Couples / Bachelors | Freezer capacity: 16L, Fresh food capacity: 169L\r\n    Energy Rating: 5 Star- Best in class efficiency\r\n    Manufacturer warranty: 1 year on product, 10 years on compressor T&C\r\n    Smart inverter compressor: Unmatched performance, great savings and super silent operation\r\n    Shelf Type: Toughened Glass with Frame | No. Of Shelves: 2\r\n    Base stand with Drawer for additional space for non-refrigerated food items like potatoes and onions etc.\r\n\r\n    Included in the box: 1 Refrigerator Unit, User Manual, / Keys, Ice tray, Egg tray\r\n    Special Features: Stabilizer free operation (90~310V), Moist \"N\" Fresh, Tray Vegetable (12.6 Ltr.), Chiller, Door Basket, Fast in ice making; Lock; Smart Connect; Solar Connect; Anti-rat bite (Sleeve); Anti-bacterial gasket \r\n\r\n', '648d9debcd75a.jpg', '180.00', 'fridge'),
(17, 2, 'Whirlpool 184 L 2 Star Direct-Cool Single Door Refrigerator', 'Whirlpool ', '\r\n    Single door refrigerator with Insulated Capillary Technology\r\n    Capacity: 184 liters for families with 2-3 members\r\n    Energy Rating - 2 Star energy efficiency\r\n    Insulated Capillary Technology-In Insulated Capillary Technology, the capillary which carries the refrigerant from the compressor to the freezer is surrounded by super cold gas leading to benefits such better compressor efficiency, faster cooling and 9 Hours* cooling retention in the refrigerator.\r\n    Special Feature - Stabilizer free operations even in high voltage fluctuations between (130V - 300V)\r\n    Brand Specific Features - Upto 9 hours of cooling retention during power cuts, Easy Manual Defrosting, Jumbo Storage Up To 3, 2L Bottle Storage, Insulated Capillary Technology, Auto Connect To Home Inverter, Large Vegetable Crisper, Honey Comb Lock In Technology & Quick Chill Zone\r\n', '648d9e47631a8.jpg', '210.00', 'fridge'),
(18, 2, 'Haier 175L 2 Star Direct Cool Single Door Refrigerator', 'Haier ', '\r\n    Direct-cool Refrigerator: Economical and Stylish with External Bar Handle.\r\n    Capacity 175 Litres: Suitable for families with 2 to 3 members or bachelors.\r\n    Energy Rating: 2 Stars - Energy Efficiency\r\n    Manufacturer Warranty: 1 year on product, 10 years on compressor.\r\n    Storage or Interior description : Fresh food capacity : 161 Ltr | Freezer capacity : 14 Ltr |drawers : 1, shelves : 2| Shelf Type : Toughened Glass |Lage vegitable box |Anti-bacterial gasket\r\n    Special Features: Stabilizer free operation, Vegetable Box, Connect Home Inverter, Anti-bacterial Gasket\r\n    Diamond Edge Freezing Technology: Firm ice formation and better cooling retention in this Haier direct cool refrigerator.\r\n\r\n    Item Dimensions: 57x53.30x111.30(LxWxH) | Weight : 31Kg\r\n    Included in the box: 1 Refrigerator Unit, Egg Tray, Ice Tray, User Manual, Keys }\r\n\r\n', '648d9eee0c73a.jpg', '180.00', 'fridge'),
(19, 3, 'Whirlpool 467 L 2 Star IntelliFresh Inverter Frost Free Double Door Refrigerator', 'Whirlpool ', '\r\n    The star rating changes are as per BEE guidelines on 1st Jan 2023\r\n    Frost Free Double Door Refrigerator : 5-In-1 Convertible\r\n    Capacity: 467 liters suitable for medium to large sized family\r\n    Energy Rating : 2star\r\n    5-In-1 Convertible : All Season Mode, Chef Mode, Dessert Mode, Party Mode, Deep Freeze Mode\r\n    Special Features : Stabilizer free operation even in high fluctuation voltage between (95V - 300V)\r\n    Brand Feature : 15 Days Of Garden Freshness, Microblock Technology, Freshonizer, Honeycomb Moisture, Freshflow Air Tower\r\n', '648da0876be78.jpg', '230.00', 'fridge'),
(20, 3, 'LG 185 L 4 Direct-Cool Smart Inverter Compressor Single-Door Refrigerator', 'LG', '\r\n    Direct Cool Refrigerator: Economical and stylish\r\n    Capacity 185 liters: Suitable for families with 2 to 3 members and bachelors| Freezer capacity: 16L, Fresh food capacity: 169L\r\n    Energy Rating: 4 Star - High energy efficiency\r\n    Smart inverter compressor: Unmatched performance, great savings and super silent operation \r\n', '648da0e49859d.jpg', '190.00', 'fridge'),
(21, 3, 'AmazonBasics 564 L Frost Free Side-by-Side Refrigerator with Water Dispenser', 'AmazonBasics ', ' The star rating changes are as per BEE guidelines on or before 1st Jan 2023;Side-by-side refrigerator with Water Dispenser and Auto Defrost technology that prevents excess ice build up automatically\r\n564 L capacity: Suitable for the daily requirements of a family with 5 or more members; Please note that Left side of the refrigerator is Freezer & right side is regular Fridge;Warranty: 1 year on product & 5 years on compressor for malfunction arising from manufacturing defects. For claiming warranty, A) Go to Your orders section, B) select the product, C) Click on Get product support and D) schedule an appointment. No need to call anyone and wait in a queue. Hassle free process. Paperless Experience with complete visibility to every step of your warranty claim.\r\nMulti airflow system ensures smooth airflow into the storage compartments for uniform cooling; Comes with in-built LED Display Panel that allows instant control and access to the temperature settings, making it convenient and easy to use\r\nOne gas refill/top-up will be provided free of cost during the first year of warranty post which they will be chargeable ', '648da8843c586.jpg', '250.00', 'fridge'),
(22, 3, 'Samsung 7 Kg 5 Star Inverter Fully Automatic Top Loading Washing Machine', 'Samsung ', '\r\n    Fully-Automatic Top Load Washing Machine: Affordable With Great Wash Quality, Easy To Use\r\n    Capacity : 7 Liters: Suitable For Families With 3 To 4 Members\r\n    Star Rating : 5 Star: Best In Class Efficiency\r\n    1400 RPM: Higher spin speeds helps in faster wash and drying\r\n    Wash Programs: 8 No.of Programs - [Bedding, Delicates, Eco Tub Clean, Energy Saving, Jeans, Normal, Quick Wash, Rinse + Spin]\r\n    Drum Type: Diamond| Body material: Stainless Steel\r\n\r\n    Key Performance Features: [Eco Bubble, BubbleStorm, Dual Storm, Auto Restart, Child Lock, Delay End, Magic Filter, Soft Closing Door, Tempered Glass Window]\r\n    Net Dimension (WxHxD) 540 x 988 x 568 mm | Included In the Box: ‎‎1N Machine Unit, N1 User Manual, 1N Installation Guide\r\n\r\n', '648da92e1f3db.jpg', '140.00', 'washing machine'),
(23, 3, 'NU 9 Kg Semi-Automatic Top Load Washing Machine with Soft Close Premium Toughened Glass Lid ', 'NU', 'Semi-automatic top load washing Machine: Economical, Low water and energy consumption, involves manual effort; Machine has both washing and drying functions\r\nKey Features: Spin tub capacity 5.5 kg, Mechanical control method, Wash Timer: 15 minutes, Wind jet dry, Spin Timer: 10 Minutes, Soak: 20 Minutes\r\nRoller Jet Pulsator added friction to the clothes, removing dust & mites. This results in a better quality wash\r\nSpecial Features: Extra wide Toughened glass lid for both Wash Drum and Spin Drum. Lint Collector, Unidirectional Wheel, Rust Free Plastic Base\r\n1300 RPM: higher spin speeds helps in faster drying\r\nCapacity 9.0 Kg: Suitable for large families ', '648da9825f6c4.jpg', '130.00', 'washing machine'),
(24, 3, 'Whirlpool 20 L Solo Microwave Oven ', 'Whirlpool ', '\r\n    20L Capacity with Superior Powder Coated Cavity\r\n    Solo Microwave Freatures: Reheating, Defrosting and Cooking.\r\n    Brand does NOT provide starter kit with this product\r\n   \r\n    Feather Touch Control with LED Display\r\n    5 Power Levels\r\n    Components Included : 1 Unit Microwave, Warranty card & User Manual.\r\n', '648daa2f959c7.jpg', '120.00', 'microwave'),
(25, 3, 'Voltas Beko 25 L Convection Microwave Oven', 'Voltas ', '\r\n    Digital Display Multitasking in kitchen is now all the more easy with VoltasBeko microwave ovens. The advanced feather touch digital display ensures you can keep an eye on food being cooked even when you are busy doing other chores in the kitchen.,\r\n    Active Defrosting The revolutionary Active Defrost technology in VoltasBeko microwave ovens makes sure your food remains frost free and saves you the hassle of defrosting manually. Retain the freshness and nutrition of your food with Active Defrost.,\r\n    Microwave Type : Convection Cavity Capacity : 25 L Maximum Microwave Power : 1400,\r\n    Product Color : Black Microwave Control Type : Electronic No. of Microwave, Power Levels : 10,\r\n    Auto cooking - 10 programs,\r\n    Active defrost,\r\n    Large turntable,\r\n', '648dabb299cdf.jpg', '130.00', 'microwave'),
(26, 3, 'Samsung 28 L Convection Microwave Oven ', 'Samsung ', '\r\n    28L : Suitable for large families,\r\n    Convection Microwave Oven: Can be used for baking along with grilling, reheating, defrosting and cooking,\r\n    Control : Touch Key Pad (Membrane) is sensitive to touch and easy to clean,\r\n    Programs : Auto Reheat/Cook, Indian Recipe, Dough Proof/Curd, Convection, Grill, Microwave, Power Defrost, Combi (Convection + Grill), Combi (Convection + Microwave), Child Lock, Turntable On/Off, Deodorisation, Clock, Eco Mode, 30 sec +,\r\n    Special Features : Various Cooking Mode, Convection Temperature (40~200 ℃), Preheat, Clock, Auto Programs, Auto Cook, Sound on/off, Ceramic Enamel Cavity,\r\n', '648dac4a2b972.jpg', '150.00', 'microwave'),
(27, 2, 'LG 20 L Solo Microwave Oven ', 'LG', '\r\n    20L Capacity: Suitable for bachelors & small families,\r\n    Solo: Can be used for reheating, defrosting and cooking, Microwave Frequency(MHZ): 2450,\r\n    Brand does NOT provide starter kit with this product,\r\n    Control: Touch Key Pad (Membrane) is sensitive to touch and easy to clean,\r\n    Child Lock: Ensures complete safety especially for homes with small children,\r\n    Special features: 44 auto cook menu options with 28 Indian dishes\r\n    Also included in the box: Warranty card, user manual,\r\n', '648dad0722dab.jpg', '140.00', 'microwave'),
(28, 2, 'Panasonic 20L Solo Microwave Oven (NN-SM25JBFDG,Black) ', 'Panasonic ', ' 20L capacity: Suitable for bachelors & small families; power + innovation 800 watts of high power for fast, Even cooking and delicious results,\r\nRe-Heat & Defrost: Auto programmed reheat and defrost modes ensure even heating or defrosting of food without compromising on the textures of flavour.\r\nControl: 5 Power Levels for better cooking as per the requirements,\r\nVapor Clean: Keep oven odor free and stain free with the touch of a button,\r\nQuick Minute Timer: Monitor cooking with easy to set single minute intervals,\r\nCompact design: This countertop microwave with Glass turntable is compact, allowing you to devote less space to electronics and more to interior capacity.\r\nOther Features: Heat Resistant Glass Door, Epoxy Gray Cavity Coating.', '648dad66180ee.jpg', '130.00', 'microwave'),
(29, 2, 'Redmi 108 cm (43 inches) Android 11 Series Full HD Smart LED TV L43M6-RA/L43M7-RA (Black) ', 'Redmi', ' Resolution : Full HD (1920x1080) resolution | Refresh Rate : 60 Hertz | 178 Degree wide viewing angle,\r\nConnectivity: 2 HDMI ports to connect set top box, Blu-Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices | 3.5mm to connect your headphones | Bluetooth 5.0 to connect Bluetooth speakers, earphones and TWS earphones,\r\nSound: 20 Watts Powerful Stereo Speakers | Dolby Audio | DTS Virtual: X and DTS-HD | Dolby Atmos pass through ARC port,\r\nSmart TV Features : Android TV 11 | Chromecast built-in | PatchWall 4 with IMDb integration | Kids Mode with Parental Lock | 75+ Free Live Channels | Universal search | Language Universe (16+ Languages) | Indias Top 10 | Miracast |, Supported Apps: Prime Video | Netflix | Disney + Hotstar | YouTube | Apple TV | 5000+ apps from Play Store | Auto Low Latency Mode | Quad core processor | Dual band Wi-Fi | 1GB RAM + 8GB Storage,\r\nDisplay: A+ Grade LED panel | Vivid Picture Engine | Detailed Picture Controls | Ultra bright screen | Dynamic contrast | Dynamic backlight. ', '648dae5f0b0ea.jpg', '280.00', 'tv'),
(30, 2, 'LG 108 cm (43 inches) 4K Ultra HD Smart LED TV 43UQ7500PSF (Ceramic Black) ', 'LG', ' Resolution: 4K Ultra HD (3840x2160) | Refresh Rate: 60 hertz,\r\nConnectivity: Wi-Fi (Built-in) | 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices | eARC | Bluetooth 5.0 | Optical | Ethernet,\r\nSound: 20 Watts Output | 2.0 Ch Speaker | AI Sound (Virtual Surround 5.1 up-mix) | Auto Volume Levelling | Bluetooth Surround Ready,\r\nSmart TV Features: AI ThinQ & WebOS 22 with User Profiles | Game Optimizer & Dashboard | α5 Gen5 AI Processor 4K | Unlimited OTT App Support: Netflix, Prime Video, Disney+ Hotstar, Apple TV, SonyLIV, Discovery+, Zee5 | ALLM & HGiG Mode | HDR 10 Pro & Active HDR,\r\nDisplay: 4K Ultra HD LED Display | 4K Upscaler | AI Brightness Control .', '648daea1cbf62.jpg', '300.00', 'tv'),
(31, 2, 'OnePlus 126 cm (50 inches) Y Series 4K Ultra HD Smart Android LED TV 50Y1S Pro (Black) ', 'OnePlus ', 'Resolution: 4K Ultra HD (3840x2160) | Bezel-less Design,\r\nConnectivity: Dual-band Wi-Fi | 3HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices,\r\nSound : 24 Watts Output | Dolby Audio | Dolby Atmos Decoding,\r\nSmart TV features: Android TV | OnePlus Connect Ecosystem| Google Assistant | , Chromecast, Miracast, DLNA | Auto Low Latency Mode | Supported Apps : Netflix, Youtube, Prime Video, Hotstar, SonyLiv, Hungama, JioCinema, Zee5, Eros Now, Oxygen Play,\r\nDisplay: 1 billion colors | Gamma Engine with MEMC | Decoding of HDR10+, HDR10, HLG .', '648daef888c76.jpg', '270.00', 'tv'),
(32, 2, 'TCL 80.04 cm (32 inches) Bezel-Less S Series HD Ready Smart Android LED TV 32S5400A (Black)', 'TCL ', ' Resolution: 1366 x 768 Pixels | Refresh Rate: 60 Hertz,\r\nConnectivity: 2 HDMI Ports to connect set top box, Blu Ray players, gaming console | 1 USB Port| 1 Headphone output,\r\nSound: 24 Watts Output | Dolby Audio MS 12 Y,\r\nSmart TV Features: Google TV |In-Built Wi-Fi | Screen Mirroring | 1.5 GB RAM | 16 GB ROM | 64-bit Quad Core Processor | In-Built Apps: Netflix, Prime Video, Disney+Hotstar,\r\nDisplay: A+ Grade Panel | 178 Degree Wide Viewing Angle | AI Picture Engine 2.0 | Dolby Audio | HDR 10 |Micro Dimming |Bezel-Less Design. ', '648daf58e5d68.jpg', '250.00', 'tv'),
(33, 3, 'Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL (Black)', 'Samsung ', ' Resolution : Crystal 4K Ultra HD (3840 x 2160) | Refresh Rate : 50 Hertz,\r\nConnectivity: 3 HDMI ports to connect set top box, Blu-ray speakers or a gaming console | 1 USB ports to connect hard drives or other USB devices,\r\nDisplay: Ultra HD (4k) LED Panel | One Billion Colors | New Bezel-less Design | Supports HDR 10+ | PurColor | Mega Contarst | UHD Dimming | Auto Game Mode,\r\nSound: 20 Watts Output | Powerful Speakers with Dolby Digital Plus | Q Symphony,\r\nSmart TV Features : Prime Video, Hotstar, Netflix, Zee5 and more | Voice Assistant - Bixby & Alexa | Tap View | PC Mode | Universal Guide | Web Browser | Screen Mirroring .', '648daffbb6011.jpg', '260.00', 'tv'),
(34, 3, 'Sony Bravia 108 cm (43 inches) 4K Ultra HD Smart LED Google TV KD-43X74K (Black) ', 'Sony ', ' Resolution: 4K Ultra HD (3840 x 2160) | Refresh Rate: 60 Hertz | 178 Degree wide viewing angle,\r\nConnectivity: 3 HDMI ports to connect set top box, Blu Ray players, gaming console | 2 USB ports to connect hard drives and other USB devices,\r\nSound : 20 Watts Output | Open Baffle Speaker| Dolby Audio | Clear Phase\r\nSmart TV Features: Google TV | Watchlist | Voice Search | Google Play | , Chromecast | Netflix | Amazon Prime Video | Additional Features: Apple Airplay | Apple Homekit |Alexa,\r\nDisplay: X1 4K Processor | 4K HDR | Live Colour| 4K X Reality Pro | Motion Flow XR100. ', '648db063ba6bf.jpg', '250.00', 'tv'),
(35, 3, 'VW 80 cm (32 inches) Playwall Frameless Series HD Ready Android Smart LED TV VW3251 (Black)', 'VW ', ' Resolution: HD Ready (1366 X 768) | Refresh Rate: 60 Hertz | Viewing Angle: 178 Degrees,\r\nConnectivity: HDMI Ports to connect Set-Top Box | Blu Ray players | Gaming Console | USB Ports to connect Hard Drives & other USB devices,\r\nSound: 20 Watts Output | Power Audio | Music Equalizer\r\nSmart TV Features: Built-in Wi-Fi | Screen Mirroring | M-Cast | Video Streaming | Multimedia Connectivity | PC Connectivity,\r\nDisplay: A+ Grade Panel | IPE Technology | True Colour | Frameless Design. ', '648db0f11f30f.jpg', '210.00', 'tv'),
(36, 3, 'Sony SA-D40 4.1 Channel Multimedia Speaker System with Bluetooth (Black) ', 'Sony', '\r\n    4.1 channel multimedia speakers, CENTRE SPEAKER ENCLOSURE TYPE and FRONT SPEAKER ENCLOSURE TYPE: Bass Reflex,\r\n    Enjoy powerful bass with large sub-woofer and 80W output,\r\n    Enjoy wireless music with mobile through Bluetooth streaming,\r\n    Designed for use with TVs, PCs and music players,\r\n    USB port for easy connectivity,\r\n    Stylish black gloss speaker finish,\r\n    Supplied with remote control. Front Speaker Dimensions (W x H x D): 10.6 x18.8 x9.6cm,\r\n    Country of Origin: China.\r\n', '648db3326810d.jpg', '110.00', 'speaker'),
(37, 3, 'HP Multimedia DHS-2101 HD Speaker with 3.5mm Audio Jack for Desktop Office Home Stereo Small Speaker', 'HP', '\r\n    This Renewed product is tested to work and look like new with minimal to no signs of wear & tear; the product comes with relevant accessories and is backed by a minimum six month seller warranty; box may be generic,\r\n    360 ° surround sound: High and low pitch unit speaker, cooperate with each other to better interpret the music. DSP technology, especially for the bass effect is optimized to bring more music effect,\r\n    Treble clear bass shock: DSP advanced signal processing technology to optimize sound and express different music styles,\r\n    Metal mesh cover is dustproof and does not fade: The bellows outer cover is formed by one-time stamping with all-metal mesh, which is not easy to deform and fade, and is as long as new,\r\n    Easy to Connect to External Devices These 2.0 compact speakers are compatible with a number of digital devices like your smartphones, laptops, PCs and music players. You can connect these digital devices with the help of its USB connectivity feature.\r\n', '648db3973f4dc.jpg', '140.00', 'speaker'),
(38, 3, 'Philips Convertible Soundbar MMS8085B/94 2.1 Channel 80W with Multiple-Connectivity Option (Black) ', 'Philips ', '\r\n    EYE CATCHING DESIGN: Sleek yet sturdy built to add class to the area to be set..Bluetooth range: Line of sight, 10M or 30FT,\r\n    CONVERTIBLE SOUNDBAR: Being versatile, the soundbar can be placed horizontally or can stand on the floor, converting it into the perfect multimedia tower speaker system.\r\n    CONNECTIVITY: The speaker system comes with multi-connectivity options like wireless streaming via BT and one can also use other inputs like USB, audio-in, 2RCA to 2RCA cable and SD card input. There is a built-in FM radio as well.\r\n    MULTIMEDIA SPEAKERS: This multimedia speaker system can be used with Computers, Gaming Consoles, Televisions, Smartphones or Tablets, DVD Players or Music Players.\r\n    SUBWOOFER: It comes with an elegant and convenient speaker-top volume and power control access.\r\n    BASS: The Philips speakers provide good sound quality with a rich bass experience from a loudspeaker box system to enhance your listening experience.\r\n    REMOTE CONTROL: Sit back, relax and take control of your entertainment with the press of a button on the remote control that comes along with it.\r\n', '648db418c853a.jpg', '190.00', 'speaker'),
(39, 3, 'Amazon Basics Bluetooth Speaker, IPX5 Waterproof, TWS Function, 9W, Powerful Bass, BT 5.0, Up to 15hrs Playtime*, microSD Card Slot, AUX Input, USB Su', 'Amazon Basics', ' The Amazon Basics 9W Bluetooth speaker is a lightweight, compact, portable speaker which is easy to carry around.\r\nComes with the latest Bluetooth version 5.0 which speeds up pairing.\r\nThe built-in rechargeable battery has a capacity of 2000 mAh which takes 8 hours to charge up completely, delivering a playback time of up to 15 hours.\r\nIPX5 certification ensures that the speaker is dust, water, and splash-proof.\r\nComes with multi-connectivity options like BT/USB & microSD card/AUX.\r\nComes with features like TWS function, call function, and volume control.\r\nThe TWS function allows you to magnify the sound by connecting another Amazon Basics 9W speaker. ', '648db48a3ed6c.jpg', '120.00', 'speaker'),
(40, 2, 'Philips Audio MMS2625B 32W 2.1 Channel Wireless Bluetooth, Wired Multimedia Computer Speaker - Black ', 'Philips ', 'Brand : Philips Audio,\r\nModel Name : Philips Audio Mms,\r\nSpeaker Type : Monitor,\r\nConnectivity Technology : Bluetooth,\r\nSpecial Feature : Radio.', '648db508929ea.jpg', '150.00', 'speaker'),
(41, 2, 'ZEBRONICS Zeb-Juke BAR 9500WS PRO Dolby 5.1 soundbar with Wireless Satellites, Dolby Audio, 525 Watts Output Power, 16.5cm subwoofer, HDMI ARC, Optica', 'ZEBRONICS ', 'A Cinematic Sound Experience with 5.1ch real Surround Sound with Zeb-Juke Bar 9500WS Soundbar. Stream music wirelessly via bluetooth Connection or Play music via USB plug & play. Powerful Bass with 525w Power Output. Simple setup with HDMI ARC, Optical, Bluetooth, AUX Inputs. An out and out immersive experience with 5.1 channels of real surround sound.  \r\n150W Subwoofer - Room Thumping Bass\r\n\r\nExperience the depth of sound with a dedicated 150W Subwoofer with 16.51cms drivers.\r\n	\r\n225W Soundbar - Triple Drivers\r\n\r\nListen to all the little details of a sound track with a 3-driver setup.\r\n	\r\n75W x Dual Wireless Satellites\r\n\r\nPosition your speakers according to your entertainment experience with dual wireless satellite speakers, featuring a compact design.\r\n\r\n*Satellites are interconnected with a 6-meter cable and powered with a DC adapter provided inside the packaging.\r\n', '648db585aaf4d.jpg', '190.00', 'speaker'),
(42, 2, 'Panasonic 1 Ton 3 Star Wi-Fi Inverter Smart Split AC (Copper Condenser, 7 in 1 Convertible with additional AI Mode, PM 0.1 Air Purification Filter', 'Panasonic ', ' 7 in 1 Convertible Modes, Auto-convertible with additional AI Mode (converti7): It smartly detects the rooms temperature, forecast the cooling capacity and change the fan speed to provide optimal cooling through inbuilt sensors and artificial intelligence. Save energy with adjustment of cooling performance by selecting modes ranging from 40% to 90%, Full capacity and High capacity.\r\nCapacity: 1 Ton - Suitable for small sized rooms (< = 120 sq ft). Energy Star Rating: 3 Star | Annual Power Consumption: 676.37 kWh | ISEER: 3.95. The star rating is as per new BEE guidelines. 424 (Indoor) CFM Air Circulation & Ambient Temperature: 52 degree Celsius\r\nSmart AC: Control your AC with your phone now. Seamlessly adjust temperature, monitor status and change modes right from the AI enabled Miraie App on phone. Seamless hands-free operation and Voice Control with Alexa and Hey Google. Experience convenience by setting hourly temperature and customised sleep profiles.\r\nCopper Condenser Coil: Better cooling and requires low maintenance. Healthy Cooling: Equipped with the PM 0.1 Filter to provide dust free, clean air by removing the PM 0.1 particles in the air.\r\nWi-Fi Split AC with Twin Cool Inverter compressor: Variable Speed Inverter Compressor which adjusts power depending on heat load. ', '648dbba3af6b3.jpg', '300.00', 'air conditioner'),
(43, 2, 'LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (Copper, Super Convertible 6-in-1 Cooling, HD Filter with Anti-Virus Protection', 'LG', ' Split Ac With Inverter Compressor: Variable Speed Compressor Which Adjusts Power Depending On Heat Load |With AI Convertible 6-in-1 user gets a flexibility to increase or decrease cooling capacity as per requirements.\r\nCapacity: 1.5 Ton Suitable for medium sized rooms (151 to 180 sq ft.); 441/1236 (In/Out) CFM Air Circulation & Ambient Temperature: 52 degree Celsius with 2 way air swing.\r\nEnergy Rating : 3 Star - Energy efficiency | Annual Energy Consumption: 968.04 Units Per Year| ISEER Value: 4.0 (Please Refer Energy Label On Product Page Or Contact Brand For More Details) ', '648dc05516037.jpg', '290.00', 'air conditioner'),
(44, 2, 'Carrier 1.5 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,High Density Filter, Auto Cleanser', 'Carrier ', ' Split AC with Flexicool inverter Technology : Variable speed compressor which adjusts power depending on heat load | with Flexicool Convertible 4-in-1 inverter technology where user can increase or decrease cooling capacity and saves upto 50%* energy consumption.\r\nCapacity: 1.5 Ton. Suitable for Mid sized rooms (111 sq ft to 150 sq. ft); 450 CFM Air Flow & Ambient Temprature: 52 degree Celsius with 2 way Air Directional Control; Best in Class Cooling Capacity with 4800 watts.\r\nEnergy Rating: 3 Star -Energy efficiency | Annual Energy Consumption (as per energy label): 964.1 units, ISEER Value: 3.85 (please refer energy Label on product page or contact brand for more details).\r\n100% Copper Condenser Coil with Aqua Clear Protection: Prevent from rust & Corrosion; Better cooling and requires low maintenance; Uninterrupted Cooling & Maximum Comfort.\r\nKey Features: Flexicool Inverter Compressor; Convertible 4-in-1 cooling; HD Filter; Turbo Cool for Faster Cooling; Hydro Blue Coating for Long Lasting Comfort; Refrigerant Leakage Detector; Auto Cleanser; ADC Sensor. ', '648dc0e0b86e8.jpg', '320.00', 'air conditioner'),
(45, 2, 'Whirlpool 1.0 Ton 3 Star, Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling Mode, HD Filter 2023 Model, S3K1PP0, White)', 'Whirlpool ', '\r\n    Split AC with Intellisense inverter compressor: variable speed compressor which adjusts power depending on heat load. 4-in-1 Convertible with 4 cooling cooling modes through remote control to operate in different tonnages for different cooling needs.\r\n    Capacity: 1.0 Ton. Suitable for medium sized rooms (111 - 150 square feet) & Ambient Temperature: 52 degree Celsius with 2-way swing.\r\n    100% Copper Condenser Coil: Better cooling and requires low maintenance.\r\n    Key Feature : 6th sense technology, Dust Filter, Stabilizer free operation within (140 V ~ 285 V), Temperature Hidden display, Noise Level: IDU 34 dB.\r\n    Energy Rating: 3 Star, ISEER Value: 3.98, Electricity Consumption 700.18.\r\n    Special Feature : Gas Leak Indicator Prevents AC from running at low gas, Dust Filter, Stabilizer free operation, Turbo Cool, Self clean, Hidden Display, Sleek design.\r\n', '648dc1805203b.jpg', '310.00', 'air conditioner'),
(46, 3, 'Godrej 1 Ton 3 Star, 5-In-1 Convertible Cooling, Inverter Split AC', 'Godrej ', '\r\n    5-in-1 Convertible Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. Operates at a cooling capacity ranging from 40% to 110%, adjust cooling capacity at your convenience thus helps in saving energy.\r\n    Capacity (1 Ton): Suitable for small sized rooms ( up to 110 sq.ft), 400 CFM & Ambient Temperature: 52℃.\r\n    Energy rating: 3 star, Annual energy consumption: 980.37, ISEER value: 3.95 This model is as per the new star rating standards valid till 2024.\r\n    Condenser Coil: 100% copper evaporator and condenser with Blue Fin Anti-Corrosion coating that ensures durability and heavy duty performance for uninterrupted powerful cooling.\r\n    Key Features: 5-in-1 Convertible Technology with inverter compressor, i- Sense Technology, 100% copper condenser, Evaporator coils & Connecting tube, R32 refrigerent, Backlit remote, Anti-Freeze Thermostat, Silent Operation, Anti- Microbial Self Clean Technology.\r\n    Special Feature: I Sense Technology: The sensor in the remote sense the temperature around you and will control the air conditioner to match the set temperature with that of your location, providing utmost comfort.\r\n', '648dc212d4b6c.jpg', '300.00', 'air conditioner'),
(47, 3, 'Blue Star 0.8 Ton 3 Star Inverter Split Ac (Copper, Turbo Cool, Gold Fins, Comfort Sleep, Self Clean Technology, Multi Sensors, Eco Mode, Hidden Displ', 'Blue Star', '\r\n    Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load.\r\n    Capacity: 0.8 Ton Suitable for small sized rooms (up to 100 sq.ft).\r\n    Energy Rating: 3 Star. Annual Energy Consumption: 521.6 units. ISEER Value: 3.92 | The star rating is as per new BEE guidelines effective from 1st July 2022.\r\n    Copper Condenser Coil: Better cooling and requires low maintenance.\r\n    Key Features: Noise Level: 28(db); Ambient Temperature: 52 degree Celsius\r\n    Special Features: 4 in 1 Convertible Cooling Mode,Turbo Cool, Comfort Sleep,Self Diagnosis, Dust Filter.\r\n\r\n    Refrigerant Gas: R32 - Environmental Friendly - No Ozone Depletion Potential\r\n    Item Dimensions & Weight : IDU - 84.1 x 20.7 x 30.0 cm (w x d x h), Outdoor : 83.9 x 32.7 x 53.6 cm (w x d x h), IDU : 10 Kg, Outdoor : 25 Kg.', '648dc29f937f8.jpg', '320.00', 'air conditioner'),
(48, 3, 'Voltas 1 Ton 3 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 123V Vectra Elegant, White) ', 'Voltas ', '\r\n    Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. Convertible / adjustable with 4 cooling modes through remote control to operate in different tonnages for different cooling needs (20% to 120% capacity).\r\n    Capacity: 1 ton Suitable for small sized rooms ( up to 110 sq.ft) & Ambient Temperature: 52 degree Celsius.\r\n    Energy Rating: 3 Star. Annual Energy Consumption: 3300 units. ISEER Value: 3.80.\r\n    Copper Condenser Coil: Better cooling and requires low maintenance, Prevents from rust & corrosion; Increase durability; Uninterrupted cooling.\r\n    Key Features: Stabilizer free operation within 110 - 285 voltage range; Digital Temperature Display ; Noise Level: IDU - 44 (db).\r\n    Special Features: Anti Dust, Antimicrobial Protection, Anti-Corrosive Coating, LED Display, Self Diagnosis, Sleep Mode, Turbo, Adjustable Cooling.\r\n', '648dc329bf1a0.jpg', '280.00', 'air conditioner'),
(49, 3, 'K L FURNITURE Solid Sheesham Wood 6 Seater Sofa Set for Living Room | Sofa Set | Sofa Set 6 Seater', 'K L FURNITURE ', ' Dimension:Three Seater Sofa: (W) 75″; (D) 29.52; (H) 27.95 inches Two Seater Sofa: (W) 54″; (D) 29.52; (H) 27.95 inches Single Seater Sofa: (W) 34″; (D) 29.52; (H) 27.95 inches.\r\nPrimary Material: Sheesham Wood | Secondary Material: MDF |\r\nAssembly Or Installation Is Based On DIY (Do It Yourself) Basis.\r\nWe Provide The Best Quality Products. Every Product Goes Through A Tough Quality Check To Ensure That We Can Serve Our Best Way. Only Made In India Products. ', '648dc6b893242.jpg', '620.00', 'sofa set'),
(50, 3, 'Torque - Jamestown L Shape 8 Seater Fabric Sofa Set for Living Room with Center Table and 2 Puffy (Left Side, Blue) ', 'Torque ', ' PRODUCT DIMENSIONS: 6 Seater Sofa: Length 95 inches (241.3 cms), Depth: 30 inches (76.2 cms), Height: 28 inches (71.12 cms).\r\nPRIMARY MATERIAL- Solid Wood & high-density Supersoft Foam -::- UPHOLSTERY MATERIAL- Premium Fabric -::- SEATING CAPACITY- 8 seater; QUALITY - This is spaciously designed with larger depth to allow for broader seating and allowing complete relaxation until the thigh to provide with superb comfort with. The cushions you sit on are firm & Comfortable.\r\nDURABILITY & COMFORT ASSURANCE: Web suspension for back-rest and hand-rest that provides extra comfort. Webbing belt support at seat construction provides durability and high density foam will provide comfort.\r\nHIGH QUALITY: Premium quality has passed 10+ quality tests; has high tensile strength, does not lose colour while rubbing and is pilling resistant.\r\nABOUT BRAND: We manufacture entire Home Furniture - Sofas, Sofa Cum Beds, Recliners, L shape Sofa Sets, Fabric Sofas, Leather Sofas, Teakwood Beds, Mattresses, Dining Table Sets, Tables, etc.', '648dc739b54cb.jpg', '650.00', 'sofa set'),
(51, 3, 'FURNY Castilla 6 Seater Fabric RHS L Shape Sofa Set (Cream-Brown)', 'FURNY ', ' Primary Material: Solidwood, Upholstery Material: Fabric, Top Material: Wood\r\nColor: Cream-Brown, Style: Modern, Seating Capacity: 6 seater\r\nAssembly Instructions: DIY (Do It Yourself)\r\nPlease expect an unevenness of up to 1inch in the product due to differences in surfaces and floor levels. The color of the product may vary slightly compared to the picture displayed on your screen. PC/Laptop monitor or mobile display has a different capability to display colors, and every individual may see these colors differently. This is due to lighting, pixel quality and color settings.\r\nThese products are shot at location at Furny studios and adhere to strict manufacturing processes and quality assurance and eligible for return according to guidelines. Get the best in class products made of quality materials for long term furniture needs.\r\nWe have Unique Catalogue of L shape Sofa Sets, 3 seater sofas, 2 seater sofas, Sofa Cum beds, Recliner Sofas, Beds, Wadrobes, Mattresses, Dining Table Sets. Browse & get the best fit for your Homes. ', '648dc8b4c939d.jpg', '580.00', 'sofa set'),
(52, 2, 'CASASTYLE Forensta 5 Seater Fabric RHS L Shape Sofa Set (Dark Grey) ', 'CASASTYLE ', ' Package Contains : Fabric Sofa Set For Living Room| Dimensions : 4 Seater Sofa L-109, D-60, H-33 (inches)\r\nUpholstery Material : Fabric | Color : Dark Grey | Seating Capacity : 5 Seater\r\nThis Fabric Sofa Set is one of our finest wooden sofa sets in Premium Fabric offering superb comfort, look and finish as compared to other sofa sets. All Casastyle sofa sets go through rigorous checking and quality testing to meet our standards of improving customer experience while buying a sofa set. ', '648dc9997cb6f.jpg', '600.00', 'sofa set'),
(53, 2, 'CASASTYLE Stylio 8 Seater RHS L Shape Fabric Sofa Set with Centre Table & 2 Puffy (Dark Grey-Light Grey) ', 'CASASTYLE ', '\r\n    L Shaped Sofa Set for Living Rooms | PRIMARY MATERIAL- Solid Wood & high density Supersoft Air Foam -::- UPHOLSTERY MATERIAL- Premium Fabric -::- SEATING CAPACITY- 8 seater\r\n    This sofa is constructed featuring handpicked Premium fabric for a regal finish. Durable for long term use and held up by Strong legs that last a lifetime.ASSEMBLY INSTRUCTIONS- Do it By Yourself.;ROYAL LOOK - Welcome your guests into your home with pride. This sofa is the ultimate statement sofa, made for royal treatment.\r\n    We manufacture entire Home Furniture - Sofas, Sofa Cum Beds, Recliners, L shape Sofa Sets, Fabric Sofas, Leather Sofas, Teakwood Beds, Mattresses, Dining Table Sets, Tables etc. We also customize all types of furniture as per customers need.\r\n    For any kind of more product info, Product Customization, after sale service and to claim Warranty please reach us at CasaStyle Customer Support.This item is only eligible for replacement , within 10 days of delivery, in an unlikely event of damaged, defective or different/wrong item delivered to you. No returns accepted for not liking the furniture, and customer change of mind, and by definition quality of furniture.\r\n    Minor variations of fabric color are acceptable due to changes in screen color between laptop/ ipad/ mobile screen of various resolutions. Style Name: Modern; Item Shape: L-Shape; Form Factor: Sectional; Arm Style: Padded; Seating Capacity: 8. Special Features: Space Saving.\r\n', '648dca16a2016.jpg', '630.00', 'sofa set'),
(54, 2, 'Amazon Brand - Solimo Alen 6 Seater Fabric LHS L Shape Sofa Set (Blue) ', 'Amazon Brand', '\r\n    L Shaped Six-seater sofa with lounger made from high-quality fabric in blue color;Product Dimensions: Sofa set - Length (71 inch), width (30 inch), height (31 inch) and Lounger - Length (72 inch), width (30 inch), height (31 inch).\r\n    Over 30 tests conducted to ensure quality;Fabric does not lose color while rubbing.\r\n    Passed durability testing with 100 kg on each seat and backrest for 25,000 cycles;Meets Indian Standards IS 12674/ IS 5416 for performance and stringent European Safety Requirement Standard EN 12520; Warranty on manufacturing defects: 3 years;Lightweight for easy shifting.\r\n    Good ground clearance for easy cleaning below the sofa;Free from toxins and harmful chemicals like formaldehyde and AZO Dye. Please note: Sofa is delivered with the legs in a detached condition. The legs are packed in a separate package and will be installed during assembly.\r\n    Frame Material Type: Engineered Wood; Item Shape: L-Shape; Seating Capacity: 6.; Form Factor: Sectional; Arm Style: Square; Style Name: Modern.\r\n', '648dca70ec2ff.jpg', '650.00', 'sofa set'),
(55, 2, 'Tree House Nesting Triangle End Coffee Tables Nightstand Modern Furniture for Home Office Living Room Nest White Table ', 'Tree House', '\r\n    【SAFE MATERIAL】 Made of solid MDF panel material smooth UV paint and bamboo table legs, which is durable and not easily damaged. Bamboo is more environmentally friendly than wood, and it can grow in five years, which is suitable for industrial use.\r\n    【FASHION AND MODERN STYLE】 With stylish design compatible well with any decor of your room, perfect combination with other furniture accessory.\r\n    【MULTIPLE PURPOSE】Nesting tables enough for books, lamp, coffee as a side table in your living room; Great multi-purpose companion to your coffee table; Fit perfectly in a small space as bedside tables.\r\n    【EASY TO ASSEMBLE】Part of our end table has been pre-installed, you only need to screw the table legs in after receiving it; In only one minute you can get a nesting table set.\r\n    [PRACTICAL DESIGN NESTING COFFEE TABLE]--The thoughtful dimensions of the three-piece set are Large Table Size: 22*17 in.\r\n', '648dcd4b05515.jpg', '80.00', 'table'),
(56, 2, 'Amazon Brand - Solimo Persi Engineered Wood Coffee Table (Walnut)', 'Amazon Brand', '\r\n    Premium-quality sturdy and stable engineered wood coffee table for home decor.\r\n    Usage of European standard E1 board for enhanced strength and rust-resistant hardware ensures longevity.\r\n    Presence of smooth edges and being free from burrs reduce chances of accidental scrapes and cuts.\r\n    Tested for distributed loading capacity of 106 kg for table top and 68 kg for each shelf.\r\n    Absence of toxins and harmful chemicals makes it safe for usage at home or in offices.\r\n\r\n    Caution: Do not move or push without dismantling and wipe the furniture with a dry cloth for better care.\r\n    Product Dimensions:- Length: 85 cm, Width: 46 cm, Height: 44 cm\r\n    Package Contents: Amazon Brand - Solimo Persi Engineered Wood Coffee Table, Colour: Walnut .\r\n\r\n', '648dcdafbc809.jpg', '90.00', 'table'),
(57, 2, 'Al Hama End Table for The Living Room with a Metal-Framed Sofa Table and Modern Side Tables with Two Tiers in a Tea Marble Pattern-(Color -White Golde', 'Al Hama', '\r\n    Its measurements are 55.88D by 55.88W by 45.72H centimetres.… aesthetically pleasing and useful double-layer storage.\r\n    A stunning design which will create a glamourous focal point wherever used.\r\n    Material: Metal & Wood, Color : Black-Gold , White-Gold, Bearing Capacity:20 KG and with ,stable support\r\n    Perfect coordination exists between the metal frame and the powder-coated gold metal legs.\r\n    The end table can function as a laptop desk, bedroom table, coffee table, snack table, and couch table.\r\n', '648dce44cd73c.jpg', '80.00', 'table'),
(58, 2, 'Multipurpose Foldable Office Table for Home/Office Desk (Beige Color, 90 x 60 x 76 cms)', 'Generic', '\r\n    Pre Assembled (Ready to Use).\r\n    W x H: 914.4 mm x 609 mm (3 ft x 2 ft).\r\n    Finish Type: MATT.\r\n    Care Instructions: Handle With Care.\r\n    Suitable For: Dining & Kitchen, Office.\r\n', '648dced7404b5.jpg', '60.00', 'table'),
(59, 3, 'AMAZE SHOPPEE Wooden Foldable Coffee Table - Mango Wood, Light Brown - Perfect Center Table for Living Room ', 'AMAZE SHOPPEE', '\r\n    Mango wood coffee table for living room with foldable design.\r\n    Light brown color complements any living room décor.\r\n    Versatile and functional - can be used as a center table, side table or coffee table.\r\n    Compact and space-saving design with dimensions of 15 x 15 x 15 inches.\r\n    Sturdy and durable wooden construction ensures long-lasting use.\r\n    Adds a touch of elegance to your living space.\r\n    Easy to store and transport.\r\n', '648dcf419f90c.jpg', '80.00', 'table'),
(60, 3, 'Klaxon Eagan Side Table/End Table/Coffee Table (Cherry)', 'Klaxon ', '\r\n    Simple Stylish Design, Functional & Suitable for Any Room | Offers Surface Storage, Side Table for Bedroom & Living Room.\r\n    DIY - Do it Yourself Assembly Required: The product requires basic assembly and comes with Assembly instruction.\r\n    Package Contains: 1 unit of Wooden Side Table With Fittings.\r\n', '648dcf97cb3e6.jpg', '70.00', 'table'),
(61, 3, 'Al Hama Coffee Table 2 Tier Round Tea Marble Pattern Table Modern Side Tables Sofa Table with Metal Frame Light End Tables for Living Room-White-Gold', 'Al Hama', '\r\n    Its dimension 40D x 40W x 53H Centimeters…… Double-layer storage, beautiful and practical.\r\n    Material: Metal & Wood, Color : Black-Gold , White-Gold, Bearing Capacity:20 KG and with Cross structure, stable support.\r\n    The table and the powder-coated gold metal legs work together perfectly.\r\n    The durable table is constructed with good MDF and a metal frame for long-lasting durability even when used outdoors.\r\n    The end table can be used as sofa table nightstand coffee table snack table bedside table laptop desk.\r\n', '648dd035cf4cb.jpg', '90.00', 'table'),
(62, 3, 'Gautam Furniture - Modern Accent Lounge Wing Chair for Living Room Dining Room (Fabric, Grey, 1 Piece) Pre-Assembled', 'Gautam Furniture', '\r\n    Solid wood, may or may not be shaped to human contours.\r\n    Seat height-18 inch.\r\n    Chairs available in different upholstery.\r\n    Crafted from premium-quality Sheesham Wood, and wrapped in premium linen fabric, it showcases high sturdiness and durability.\r\n', '648dd0a808075.jpg', '70.00', 'chair'),
(63, 3, 'Vanshika Craft ! Natural Bamboo Mudda Weaving Beige Small Chair (Baby Kid)', 'Vanshika Craft', '\r\n    Material :- Bamboo ( Sarkanda ).\r\n    Color :- Beige.\r\n    Size :- Chair Seat Height :- 16\" Inch Seat Size :-18X 18 \".\r\n    Chair Length :- 34 \" inch.\r\n    Chair Type :- Arm Chair.\r\n    Uses :- Indoor & Outdoor.\r\n    Load Capacity :- Chair -120 KG.\r\n', '648dd0e93a26e.jpg', '50.00', 'chair');
INSERT INTO `products` (`id`, `admin_id`, `title`, `brandname`, `description`, `image`, `rent`, `category`) VALUES
(64, 3, 'Gani Wood Rocking Chair/Colonial Rocking Chair/Traditional Rocking. Armchair/Solid Teak Wood with Foot Rest (Rocking Chair with footrest) (Brown) ', 'Gani Wood', '\r\n    Material - Premium Sheesham Wood With High-Density Foam (Cushion).\r\n    Enjoy the feeling of being comfortable while you read your favorite books using our wooden rocking chair with its slim, modern design will be perfect for anyone short on space. It Provides support to relieve pain.\r\n    Chair Size - Height - 89 cm, Width - 67 cm, Depth - 150 cm. (Seating Height 42 cm).\r\n    The perfect companion for your living room or bedroom when you need to put your feet up.\r\n    This rocking chair is designed with comfort and style in mind. The elegant design of the frame makes the chair very strong and sturdy. The rocking chair provides an exceptionally comfortable and enjoyable place to relax.\r\n', '648dd15e52863.jpg', '70.00', 'chair'),
(65, 2, 'IRA Furniture Rattan Easy Chair with Cushion for Garden Balcony (Standard Size, Brown) ', 'IRA', '\r\n    Product Dimensions:: Length(31 inches),Width(25 inches), Height(39 inches)\r\n    MADE IN INDIA.\r\n    Content includes : 1 Chair, 1Cushion.\r\n    Primary Material: Rattan & Wicker. Cushion Material : Other (Mixed Cotton).\r\n', '648dd1bdaed2d.jpg', '60.00', 'chair'),
(66, 2, 'Scandinavian Modern Simple backrest Leisure Rattan Chair Bedroom Makeup Chair', 'Generic', 'Brand : Generic.\r\nColour : Navy Blue.\r\nMaterial : Rattan.\r\nIncluded Components : Cushion.\r\nShape : L-Shape.\r\nModel Name : Rattan chair.\r\nForm Factor : Loveseat.\r\nSeat Height : 18 Inches.\r\nSeat Length : 24. ', '648dd230c0cea.jpg', '70.00', 'chair'),
(67, 2, 'MJ FURNITURE Wooden King Size Bed - Solid Sheesham Wood Double Cot Without Storage- Stylish and Functional Furniture for Your Bedroom (Honey Finish) ', 'MJ FURNITURE', '\r\n    Dimensions(Inch) : 81 L x 74 W x 34 H.\r\n    Dimensions (Cm) : 205.7 L x 188 W x 86.4 H.\r\n    Mattress Size(Inch) : 78 L x 72 W.\r\n    Storage : Without storage.\r\n    Premium quality sheesham wood construction.\r\n    King size double cot without storage bed.\r\n    Easy to assemble with included hardware and instructions.\r\n    Superior craftsmanship ensures durability and longevity.\r\n    Ideal for anyone who values both style and comfort in their bedroom furniture.\r\n\r\n', '648e8df3c8828.jpg', '500.00', 'bed'),
(68, 2, 'Amazon Brand - Solimo Medusa Engineered Wood Queen Size Bed Without Storage - (Walnut Finish_Brown) ', 'Amazon Brand', '    Queen-size bed ideal for mattresses sized 78 x 60 inches.\r\n    Dimensions:- Width: 160 cm (62.99 in); Length: 203 cm (79.92 in); Height: 79 cm (31.4 in).\r\n    Manufactured using European standard particle board that is long lasting and resistant to stains and humidity.\r\n    Premium walnut finish coupled with an elegant design and curvilinear edges\r\n    Surpassed 20+ quality and safety tests; free from burrs and sharp edges for enhanced safety.\r\n    Underwent dynamic loading testing; durability tested for 100 kg over 10,000 cycles and rigorously bed-edge stability tested for 100 kg over 1,000 cycles\r\n    Safe to use; free from harmful toxins and chemicals.\r\n    Care Instructions:- Do not move or push without dismantling. Avoid using a wet cloth to wipe clean.\r\n    Package Contents:- 1 x Medusa Engineered Wood Queen Bed (Walnut Finish) .\r\n', '648e8e793a091.jpg', '480.00', 'bed'),
(69, 2, 'MAMTA DECORATION Engineered Wood King Size Bed with Box Storage Upholstered Headboard Wooden Bed for Bedroom Living Room Home (Brown Finish) ', 'MAMTA DECORATION', '\r\n    King Size Bed Dimension: Length (193 cm), Width (182.88 cm), Height (122 cm).\r\n    Compatible Mattress Size: 78x70 Inchh (Not Included).\r\n    Material: Engineered Wood Bed; Color: Brown Finish; Package Content: 1 Solid Wood Bed with Box Storage.\r\n    Manufactured using European standard particle board that is long lasting and resistant to stains and humidity.\r\n    The wooden double bed requires basic self-assembly at the customers end and comes with self-assembly (DIY) instructions along with necessary.\r\n', '648e8f2438015.jpg', '500.00', 'bed'),
(70, 2, 'Trevi Bed | Double Queen Bed | Bolton Engineered Wood Without Storage in Teak Finish ', 'Trevi ', '    Unique Design For Your Bedroom.\r\n    100% Termite Resistant; High Strength Engineered Wood.\r\n    Built-In Storage Headboard Design.\r\n    Assembly Instructions: Require Assembly.\r\n', '648e8fd046790.jpg', '510.00', 'bed'),
(71, 2, 'AIREN DECORE Solid Sheesham Wood King Size Double Bed with Box Storage for Bedroom Furniture Wooden Palang for Living Room - Walnut Finish ', 'AIREN DECORE ', '\r\n    King Size Bed Dimension:- Length (205 Cm), Width (190 Cm), Height (90 Cm). Mattress Size: 78 X 72 Inches (Not Included);Material: Sheesham Wood Bed; Color: Walnut Finish; Package Content: 1 Bed With Box Storage.\r\n    Material: Sheesham Wood Bed; Color: Walnut Finish; Package Content: 1 Bed With Box Storage.\r\n    The Wooden Palang For Home Has An Ideal That Can Be Placed Easily In Your Bedroom.The Wooden Bed With Box Storage Comes With A Simple And Contemporary Design. It Is Made From Solid Wood Which Ensures Durability And Strength.;The Wooden Double Bed Requires Basic Self-Assembly At The Customers End And Comes With Self-Assembly (Diy) Instructions Along With Necessary.\r\n    In Absence Of A Service Lift, Our Delivery Partner Will Only Deliver To The Ground Floor Of Your Apartment. Extra Charges Applicable Per Floor On Delivery To The Customers Floor (On Request) In Such Cases.;If You Find Manufacturing Issues , Defect Parts Will Be Return & Replaced, But Customers Have To Pack The Product Back In The Original Condition For Arranging The Successful Return Pickup For Replacement.\r\n    If You Find Manufacturing Issues , Defect Parts Will Be Return & Replaced, But Customers Have To Pack The Product Back In The Original Condition For Arranging The Successful Return Pickup For Replacement.\r\n', '648e906747c28.jpg', '530.00', 'bed'),
(72, 3, 'BLUEWUD Pollo Engineered Wood Queen Size Bed with Storage (Wenge & White) ', 'BLUEWUD ', '\r\n    Size: Queen | Dimensions: Length- 201.5Cm (79.3\") | Breadth- 155.5Cm (61.2\") | Height 74.1Cm (29.1\").\r\n    Made of Particle Board (High grade prelam engineering wood with natural wood grain finish).\r\n    Recommended Mattress Size: 78 X 60 Inches Storage Type: Box Storage\r\n    FREE PRODUCT ASSEMBLY service provided by the seller.\r\n    Maximum Weight Capacity: 180 KG.\r\n', '648e90df663ff.jpg', '500.00', 'bed'),
(73, 3, 'Furniseworlds Sheesham Wood King Size Poster Bed Wooden Double Bed Cot Bed Furniture for Bedroom Home and Hotel (Honey Finish) ', 'Furniseworlds ', '\r\n    Wooden Bed Dimension: Length (84 Inch), Width (76 Inch), Height ( 75 Inch); Double Bed Material: Sheesham Wood|Color: Honey Finish|Style: Modern.\r\n    Elegant And Vintage Design Of The Wooden Bed Makes It Well Match With Many Home Decoration.\r\n    The Full Size Bed Has Been One Of The Most Essential And Integral Part Of The Bedroom Furniture.\r\n    This Cot Bed Requires Basic Self Assembly At Customers End And Comes With Self Assembly Instructions Along With Necessary Accessories.\r\n    Care Instructions: Wipe With Dry Cloth; Assembly Instructions: Diy.\r\n', '648e912fc378d.jpg', '550.00', 'bed'),
(74, 3, 'Wakefit Study Table| Study Table for Students, Computer Table for Home, Desks with One Shelf (Athena - Brown) ', 'Wakefit ', '\r\n    PRODUCT DIMENSIONS: Length = 120 cm, Width = 60 cm, Height = 79.5 cm (47.2 inches x 23.6 inches x 31.3 inches).\r\n    PHYSICAL ATTRIBUTES: Product Material: High grade prelam engineering wood with natural wood grain finish | Product Color: Columbian Walnut | Product Weight: 42 Kgs.\r\n    ASSEMBLY: FREE of cost, by carpenters at the time of delivery.\r\n    STORAGE SPACE: 1 drawer, 1 closed compartment.\r\n    ADDITIONAL BENEFITS: Termite Resistant. Water Resistant. Easy Clean.\r\n    CARE INSTRUCTIONS: Wipe regularly with a soft, clean cloth. Avoid exposure to direct sunlight and moisture.\r\n', '648e9212abf5f.jpg', '210.00', 'desk'),
(75, 3, 'Amazon Brand - Solimo Prize Engineered Wood Finish Study Desk (Black) ', 'Amazon Brand', '\r\n    Study desk for family and home office use;Dimensions:- Length: 102 cm (40.15 in), Width: 50 cm (19.68 in), Height: 75 cm (29.52 in); Simple and timeless design in a black finish gives an elegant look and feel;Made using premium quality engineered European standard E1 board for increased sturdiness and stability.\r\n    Rust-resistant hardware and accessories ensures longevity;Durable structure with load bearing capacity of 62 kg on table and 10 kg on each shelf.\r\n    Spacious design with ample storage for laptop, books, study materials, stationary etc…;Safe to use; free from toxins, chemicals, burrs and sharp edges.\r\n Assembly Required: Carpenter assembly is provided by seller. Care Instructions: Do not move without dismantling. Use a dry cloth to wipe clean. Package Contents: 1 Engineered Wood Study Desk; Finish: Black.\r\n    Target Audience Keywords: Adults; Care Instructions: Wipe With Dry Cloth; Assembly Instructions: Require Assembly; Style Name: Modern; Included Components: 1 Study Table With Fittings.\r\n', '648e92b94f236.jpg', '190.00', 'desk'),
(76, 3, 'SUNNYCRAFT Modern Simple Style PC Computer Study Writing Wood Office Desk, Study Desk,Folding Desk', 'SUNNYCRAFT ', 'Brand : SUNNYCRAFT.\r\nShape : Rectangular.\r\nDesk design : Computer Desk.\r\nProduct Dimensions : 60D x 90W x 75H Centimeters.\r\nColour : Black,White.\r\nStyle : Modern.\r\nBase Material : Wood.\r\nTop Material Type : Engineered Wood.\r\nSpecial Feature : Portable, Convertible, Lightweight, Foldable.\r\nRoom Type : dining, Living Room, Bedroom.', '648e933feb1dd.jpg', '190.00', 'desk'),
(77, 2, 'Decornation Well Finished Study Table Desk, Reading Table, Wood Table, Writing Desk for Home and Office Made of MDF Solid Wood (White)', 'Decornation ', '\r\n    Material: The tabletop is made of MDF material which is very durable and does not damage easily in spite of rough handling. This top is mounted on four legs that are made from solid wood and offer stability to this table.\r\n    Sturdy & Modern Design: The overall design looks very unique and features a perfect blend of utility and trendiness. The design is also very sturdy which allows you to keep your computer, laptop and other precious things on the table without any fear.\r\n    Multipurpose & Convenient: This Zane office table can be kept in your office as well as your home. Its stylish yet functional design allows you to use this table as a study desk, computer desk, writing table etc.\r\n    Easy to Move & Clean: The compact and sturdy design of this table makes it very easy to move. The minimalist design and smooth surface of the table ensure that you find it very easy to clean.; Dimensions: This office table measures 42\"x 20\"x 29\" (L x W x H). The appropriate height of this table makes it a utilitarian addition to your office or home.\r\n    Assembly Instructions: Require Assembly; Top Material Type: Engineered Wood; Included Components: Light Kit Inlcuded; Style Name: Scandinavian; Finish Type: Painted..\r\n', '648e981f29983.jpg', '220.00', 'desk'),
(78, 2, 'LAD Workspaces The X Table Engineered Wood Study Table, Laptop, Computer Table Desk for Home & Office White 3ft', 'LAD ', '\r\n    Small Size - 90Cms (Wide) X 60 Cms (Deep) X 75 Cms (High) Offers You A Large And Efficient Space To Work.\r\n    Robust Design - Table Top Is Premium Particle Board (High Grade Prelaminated Engineering Wood With Natural Wood Grain Finish) Which Is Mounted On A Well Enginered Metal Frame (Powder Coated Mild Steel) And With Adjustable Leg Pads Which Provide Greater Stability And Comfort; Worry Free 1 Year Warranty - A 12 Month Warranty Any Against Kind Of Manufacturing Defects.\r\n    Versatility - With Modern Sleek Design, The Computer Table Can Suit Any Home, Office Dorm, School And Workspace. Wide Desktop Provides Ample Space For Computer, Monitor, Printer And Other Office Supplies As Computer Desk, Study Desk, Gaming Desk, Writing Table, Card Table, Dining Table, Etc.\r\n    Assembly - No Assembly Required. Just Remove The Packaging And Start Using From The Word Go.\r\n    Assembly Instructions: Already Assembled; Material Type: Wrought And Cast Iron; Included Components: Shade Included.\r\n', '648e989acccb3.jpg', '200.00', 'desk'),
(79, 2, 'WOODBUZZ Marvel Home Office Study Table (Engineered Wood) (White + Ocean Green) ', 'WOODBUZZ ', 'Brand : WOODBUZZ.\r\nShape : Rectangular.\r\nDesk design : Computer Desk.\r\nProduct Dimensions : 50D x 125W x 120H Centimeters.\r\nColour : White + Ocean Green.\r\nStyle : Modern.\r\nBase Material : Engineered Wood.\r\nTop Material Type : Engineered Wood.\r\nRoom Type : Office, Living Room, Bedroom.\r\nRecommended Uses For Product : Working,Gaming.', '648e9944d13e4.jpg', '250.00', 'desk'),
(80, 2, 'WELLBORN Solid Sheesham Wood 4 Seater Dining Table with 4 Chair Dining Set for Living Room Dining Set | Hotel Restaurants Dining Set | Finish - Natura', 'WELLBORN ', ' Dimensions Table - Length (114.3 CM), Width (76.2 CM), Height (76.2 CM), Chair - Length (45 CM ), Width (44.5 CM), Height (86.5 CM)\r\nPrimary Material-: Sheesham Wood, Product Material-: Sheesham Wood.\r\nAssembly Required By Customer :- Chair - Already Assemble ,| Table - Assembly Required (Need to Fix Only 4 Leg ) , Screw Driver & all Assembly Tools included in the packet. Minor assembly - No Carpenter Required.This splendid style of wooden dining table set create a beautiful impression with perception of modernization. This piece is made of natural wood crafted by traditional expertise hand. These skills are combination of traditional with contemporary craftsmanship and procedure.\r\nRequired Tool during Assemble: Wrench - Size - 12-13 or Adjustable Spanner Wrench, Nut - 8 (Come with Table) .', '648e99ef77c9d.jpg', '400.00', 'dining table'),
(81, 2, 'KENDALWOOD™ Furniture Sheesham Wood CNC Cuting Dining Table with 4 Chairs with 1 Bench - Dining Room Furniture (Finish Color:-Honey Teak with Cream Cu', 'KENDALWOOD', '\r\n    KendalWood - Manufacturing Since 1990 - Made In India Sheesham Wood Product.\r\n    Product Dimensions:Table : H 30 x W 57 x D 35; Chair : H 36 x W 18 x D 18; Seating Height - 18; Bench : H 18 x W 40 x D16 (all dimensions in inches) Chair Weight - 8 Kg | Table Weight - 22 kg . Chair Weight Load Capacity - 120Kg | Table Weight Load Capacity - 300kg | Product Finish Color - Honey Finish With Cream Cushion.\r\n    Multi Purpose Dining Table Set - Your can Enjoy your Dinner with Family on this kendalwood Solid wood dining Set , this is a 6 Seater Dining set , Dining table with 4 chair and 1 Bench, Solid wood dining set | Also can use as Study Table | Working Table | Work From Home Table Kendalwood Dining table Set is Best Gift for Housewarming And Wedding.\r\n', '648e9a7b52a7d.jpg', '420.00', 'dining table'),
(82, 2, 'Sofani Solid Sheesham Wood Crescent Dining Table 6 Seater | White & Grey Texture Top & Solid Wood Legs with 6 Premium Velvet Fabric Cushioned Chairs |', 'Sofani ', '\r\n    Product Dimension(In Inch):- Table:- Length: 60 X Width: 35 X Height: 30 | Chair:- Length: 18 X Width: 18 X Height: 36 | Seating Height:- 36\r\n    High-quality craftsmanship: The Sofani Solid Sheesham Wood Dining Table 6 Seater is expertly crafted with solid wood legs and a white marble finish table top, showcasing superior craftsmanship that adds elegance to your dining area.\r\n    Spacious and comfortable: With a 6-seater capacity, this dining table provides ample space for family and friends to gather and enjoy meals together. The accompanying 6 premium velvet fabric cushioned chairs offer exceptional comfort, allowing you to relax and dine in style.\r\n    Basic leg assembly is required on the dining table, which is quick and easy to do, allowing you to start using your new furniture in no time.\r\n    Versatile design: The combination of rosewood, white, and brown finishes gives this dining set a versatile design that complements various interior styles. Whether your decor is modern, contemporary, or traditional, this dining table seamlessly blends in with its surroundings.\r\n    Durability and longevity: Made from solid sheesham wood, this dining table is built to last. Sheesham wood is known for its sturdiness and resistance to wear and tear, ensuring long-lasting durability and a timeless appeal.\r\n    Functional and practical: Beyond its aesthetic appeal, this dining table is designed with functionality in mind. The spacious table top provides ample room for serving dishes, the solid wood legs offer stability and support. The chairs are designed to provide optimal seating comfort, making it a practical choice for everyday use in your kitchen or dining area.\r\n', '648e9af0a0dad.jpg', '400.00', 'dining table'),
(83, 2, 'Driftingwood Zig Zag Solid Sheesham Wood Dining Table 4 Seater | Wooden Four Seater Dinning Table With Cushioned Chairs For Restaurant | Dinner Table ', 'Driftingwood ', '\r\n    Product Dimension(In Inch): Table:- Length: 35 X Width: 35 X Height: 30 | Chair:- Length: 17.7 X Width: 17.7 X Height: 34.\r\n    Primary Material: Sheesham Wood | Secondary Material: Solid MDF/Plywood Depending On Availability | Product Name: Wooden Dining Table 4 Seater For Dinning Room & Kitchen.\r\n    Give Your Home A Luxurious Look With Sheesham Wooden Dining Table Sets | Fits In Your Space, Fits On Your Budget.\r\n    We Provide Quality Products. Every Product Goes Through A Tough Quality Check To Ensure That We Can Serve Our Best Way. Only Made In India Products.\r\n    If A Customer Wants To Claim Warranty , Share Photos And Videos Of Defect Parts , If We Find Manufacturing Issues , Defect Parts Will Be Return & Replaced, But Customers Have To Pack The Product Back In The Original Condition For Arranging The Successful Return Pickup For Replacement.\r\n', '648e9b67a9492.jpg', '410.00', 'dining table'),
(84, 3, 'KENDALWOOD Furniture Solid Wood Dining Table with 4 Chairs | 4 Seater Dining Set | Wooden Dining Table with Chair - Dining Room Furniture | Finish Col', 'KENDALWOOD ', '\r\n    KendalWood- Manufacturing Since 1990 - Made In India Sheesham Wood Product.\r\n    Product Dimensions (Inch): Square Table : H 30 x W 34 x D 34; Chair : H 36 x W 18 x D 18; Seating Height - 18 ( All Dimensions inch) Chair Weight - 8 Kg | Table Weight - 12 kg . Chair Weight Load Capacity - 120Kg | Table Weight Load Capacity - 300kg | Product Finish Color - Natural Honey Finish With Grey Cushion.\r\n    Material : This Dining Dining Table Fully Made By Solid Wood , Table Top - Solid Wood | Chair - Solid Wood | This Dining set Available in 3 More Different Color - Walnut , Honey Teak and Mahogany , Visit our all listing and choose your Matching Color .\r\n    Multi Purpose Dining Table Set - Your can Enjoy your Dinner with Family on this kendalwood Solid wood dining Set , this is a 4 Seater Dining set , Dining table with 4 chair and 1 Table , Solid wood dining set | Also can use as Study Table | Working Table | Work From Home Table Kendalwood Dining table Set is Best Gift for Housewarming And Wedding.\r\n    Assembly Required - Yes , FREE Furniture assembly by a background-verified expert at a scheduled time slot chosen by you.\r\n', '648e9c062ae16.jpg', '420.00', 'dining table'),
(85, 3, 'DecorNation Italiana Solid Wood 4 Seater Dining Room Set for Home, Living Room- Dining Table with Four Cushioned Chairs (White) ', 'DecorNation ', '\r\n    Best Material: Solid Wood. We focus on making high-quality furniture sets for home, office. We have made this sturdy wooden cushioned chair set with table from durable solid wood, with materials that hold heavy weight.\r\n    Durable & Modern: High quality wood connecting procedure which could make this more durable and solid. And the structure follows the scientific principle and is strong enough. Durable, easy to clean and elegant look with modern sense. The armless chairs work well in a dining room or eat-in kitchen or next to a desk in an office.\r\n    Sturdy Wooden Furniture: Sturdy Enough to be a Fully Functional and Comfortable Seat, Especially for Toddlers. Traditional Design compliments most décor. This dining table set makes for a great addition to your home. The set has an extremely modern and contemporary look that helps you set up a stylish dining space in your home.\r\n    Easy to Clean: All our tables & chairs are easy to maintain, simply spot clean with a damp towel. Assembly : Do It Yourself.\r\n    Assembly Instructions: Require Assembly.\r\n', '648e9ccfd2d53.jpg', '450.00', 'dining table'),
(86, 3, 'Apple iPhone 14 (128 GB) - Blue ', 'Apple', '\r\n    15.40 cm (6.1-inch) Super Retina XDR display.\r\n    Advanced camera system for better photos in any light.\r\n    Cinematic mode now in 4K Dolby Vision up to 30 fps.\r\n    Action mode for smooth, steady, handheld videos.\r\n    Vital safety technology — Crash Detection calls for help when you can not.\r\n    All-day battery life and up to 20 hours of video playback.\r\n    Industry-leading durability features with Ceramic Shield and water resistance.\r\n\r\n    A15 Bionic chip with 5-core GPU for lightning-fast performance. Superfast 5G cellular.\r\n    iOS 16 offers even more ways to personalise, communicate and share.\r\n\r\n', '648eab04216b4.jpg', '200.00', 'mobile'),
(87, 3, 'realme narzo N55 (Prime Blue, 6GB+128GB) 33W Segment Fastest Charging | Super High-res 64MP Primary AI Camera', 'realme', '\r\n    * With fast 33W SUPERVOOC charging, the realme narzo N55 charges up the massive 5000mAh battery from 0-50% in just 29 minutes, making your life super convenient and stress free.\r\n    * Super High-res 64MP primary AI camera allows you to shoot crisp and clear shots in any scenario with incredible detail. The flagship grade ProLight Imaging technology brings segment leading low light performance to the N55.\r\n    * Enjoy up to 12GB of Dynamic RAM made up from up to 6GB of onboard RAM and up to an additional 6GB of Dynamic RAM for next level multi tasking.\r\n    * Large 6.72” Full screen display on the narzo N55 provides a segment leading display with a centre punch hole display, 90Hz ultra smooth refresh rate, 680nits of peak brightness, and 91.4% screen-to-Body ratio.\r\n    * Flagship grade premium two tone design makes the N55 stand out from the crowd. The 7.89mm thin beauty feels easy to hold and light weight to carry around easily.\r\n', '648eab5c926d8.jpg', '150.00', 'mobile'),
(88, 3, 'Samsung Galaxy S20 FE 5G (Cloud Mint, 8GB RAM, 128GB Storage) ', 'Samsung ', '\r\n    5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM.\r\n    Triple Rear Camera Setup - 12MP (Dual Pixel) OIS F1.8 Wide Rear Camera + 8MP OIS Tele Camera + 12MP Ultra Wide | 30X Space Zoom, Single Take & Night Mode | 32MP F2.2 Front Punch Hole Camera.\r\n    6.5-inch(16.40 centimeters) Infinity-O Super AMOLED Display with 120Hz Refresh rate, 1080 x 2400 (FHD+) Resolution \".\r\n    4500 mAh battery (Non -removable) with Super Fast Charging, FAst Wireless Charging & Finger Print sensor.\r\n    IP68 Rated, MicroSD Card Slot (Expandable upto 1 TB), Dual Nano Sim, Hybrid Sim Slot, 5G+5G Dual stand by.\r\n    Disclaimer: N28 band for Stand alone 5G network is not compatible.\r\n', '648eabb11f404.jpg', '160.00', 'mobile'),
(89, 3, 'Redmi 12C (Royal Blue, 4GB RAM, 64GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh(typ) Battery', 'Redmi ', '\r\n    Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x.\r\n    Camera: 50MP f/1.8 AI Dual camera with Portrait mode & Night Mode | 5MP Selfie camera.\r\n    Display: Large 17cm HD+ display with Scratch resistant Glass and Oleophobic coating | 500nits peak brightness.\r\n    5000mAh(typ) battery with 10W charger in-box.\r\n    Dual band Wifi support ensures better throughput and connectivity.\r\n', '648eabf45fdf5.jpg', '140.00', 'mobile'),
(90, 2, 'Apple iPhone 14 Pro Max (128 GB) - Space Black ', 'Apple ', '\r\n    17.00 cm (6.7-inch) Super Retina XDR display featuring Always-On and ProMotion.\r\n    Dynamic Island, a magical new way to interact with iPhone.\r\n    48MP Main camera for up to 4x greater resolution.\r\n    Cinematic mode now in 4K Dolby Vision up to 30 fps.\r\n    Action mode for smooth, steady, handheld videos.\r\n    All-day battery life and up to 29 hours of video playback.\r\n    Vital safety technology — Crash Detection can detect a severe car crash and call for help.\r\n\r\n    A16 Bionic, the ultimate smartphone chip. Superfast 5G cellular.\r\n    Industry-leading durability features with Ceramic Shield and water resistance.\r\n    iOS 16 offers even more ways to personalise, communicate and share.\r\n\r\n', '648eaea6de8d1.jpg', '200.00', 'mobile'),
(91, 2, 'Oppo A78 5G (Glowing Black, 8GB RAM, 128 Storage) | 5000 mAh Battery with 33W SUPERVOOC Charger| 50MP AI Camera | 90Hz Refresh Rate | with No Cost EMI', 'Oppo ', '\r\n    Big 5000 mAh Battery with 33W SUPERVOOC Charging.\r\n    Super smooth experience with ColorOS 13 and 8GB RAM (+ RAM expansion up to 8GB) | 128GB ROM | Expandable Upto 1TB.\r\n    Crystal clear details with AI Camera setup 50MP + 2MP Rear Camera | 8MP Front Camera.\r\n    OPPO Glow Design with 6.56\" inch (16.66cm) 90Hz Color-Rich Display and Large Screen to Body ratio of 89.8%.\r\n    Dual Ultra Linear Stereo Speakers with ROST and flagship hardware which produce an immersive sound effect.\r\n', '648eaf17212e3.jpg', '160.00', 'mobile'),
(92, 2, 'OnePlus Nord CE 3 Lite 5G (Pastel Lime, 8GB RAM, 128GB Storage) ', 'OnePlus ', '\r\n    Camera: 108 MP Main Camera with EIS; 2MP Depth-Assist Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP.\r\n    Rear Camera Mode: Hi-res 108MP mode, 3x Lossles Zoom, Photo, Video, Nightscape, Expert, Panoramic, Portrait, Macro, Time-lapse, Slow-motion, Long exposure, Dual-view video, Text Scanner, 1080p/720p@30fps, Video zoom: 1080P@30fps, 720P@30fps, Slow motion: 720P@120fps, Time-Lapse: 1080P@30fps, Steady Video EIS support.\r\n    Display: 6.72 Inches; 120 Hz Adaptive refresh rate; FHD+(1080×2400), Colors: 16.7 Million colors, 391 ppi, Aspect Ratio: 20:9, Brightness: 550 nits (typical), 680 nits (HBM).\r\n    Operating System: Oxygen OS based on Android 13.1.\r\n    Processor: Qualcomm Snapdragon 695 5G.\r\n    Battery & Charging: 5000 mAh with 67W SUPERVOOC Endurance Edition.\r\n', '648eaf6411efd.jpg', '170.00', 'mobile'),
(93, 2, 'Apple 2022 10.9-inch iPad (Wi-Fi + Cellular, 256GB) - Blue (10th Generation) ', 'Apple ', '\r\n    Striking 10.9-inch Liquid Retina display with True Tone.\r\n    A14 Bionic chip with 6-core CPU and 4-core GPU.\r\n    12MP Wide back camera.\r\n    Landscape 12MP Ultra Wide front camera with Center Stage.\r\n    Touch ID for secure authentication and Apple Pay.\r\n', '648eb01ff1d9c.jpg', '260.00', 'tablet'),
(94, 2, 'Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz Refresh Rate| 6GB, 128GB| 2.5K+ Display (10.95-inch/27.81cm)|1 Billion Colours| Dolby Vision Atmos| Quad ', 'Xiaomi ', ' Display size: 2.5K+ Display (10.95-inch/27.81cm); Display type: IPS LCD; Display resolution: WQHD+ (2560x1600 high resolution) Dolby Vision display; Max Display brightness (650 nits); Screen refresh rate: 120Hz.\r\nCalling supported (No); 6GB RAM; 128GB ROM; Processor descriptions: Qualcomm Snapdragon 860 Octa-core processor; Operating system: Android 11; Supports DCI-P3 with over 1 billion colours.\r\nBattery power: 8720mAh, charger wattage: 22.5W, Camera Front: 8MP; Camera Back: 13MP Rear Camera with 4K recording; Camera Flash: Yes; Ultra Slim design\r\nFinger print sensor - No; Palm Rejection: Yes; GPS: No; Stylus compatible - Yes, Headphone jack (No); Compatibility with external HDD - Yes; Quad Speakers with Dolby Atmos .', '648f07f9b5c26.jpg', '220.00', 'tablet'),
(95, 2, 'Lenovo Tab M10 FHD Plus (3rd Gen) (10.61 inch (26.94 cm), 6 GB, 128 GB  and Quad Speakers with Dolby Atmos ', 'Lenovo ', ' 10.61 inch FHD 2K (2000 * 1200) display| 400 nits brightness| PPI 220| 72% NTSC; Display Type - 2K, FHD, IPS; Screen Refresh - 60Hz.\r\nCalling supported (Yes); 6 GB RAM| 128 GB ROM expandable upto 1 TB; Processor description - Snapdragon SDM 6803 processor (4 *A73, 2.4 GHz + 4 * A53, 1.9 GHz0; Operating system - Android 12.0.\r\nBattery power 7700 mAH battery, 12 hours video playback time; charger wattage - 10W, 8 MP Auto-Focus with Flash Rear Camera; 8 MP Fixed Focus Front Camera.\r\nFinger print sensor - No, GPS - Yes, Stylus compatible - Yes, Pen Supported; Headphone jack (Yes); Speaker wattage - 4W; Compatibility with external HDD - No, Use Micro SD Card.\r\nQuad speakers optimized with Dolby Atmos| Google Kids Space with Parental Control| Entertainment Space| Netflix| Amazon Music| Google One; Dual Tone Metal Body| 7.45 mm thin .', '648f088276b53.jpg', '210.00', 'tablet'),
(96, 3, 'Redmi Pad | MediaTek Helio G99 | 26.95cm (10.61 inch) 2K Resolution & 90Hz Refresh Rate Display | 4GB RAM & 128GB Storage', 'Redmi ', '\r\n    MediaTek Helio G99 Octa-Core processor | ARM Mali-G57 MC2 GPU | 4GB RAM | 128GB Internal Storage | Expandable upto 1TB with SD Card.\r\n    2000 x 1200 High Resolution | 90Hz refresh rate| 26.95cm (10.61 inch) 10 Bit Display | 1 Billion Colours | Low Blue Light Eye Protection.\r\n    Quad Speakers with Dolby Atmos | Long lasting 8000 mAh Battery | Android 12 | MIUI 13 with Android & security updates.\r\n    8MP Rear Camera with FHD recording | 8MP Front Camera with 105⁰ FOV | Slim Metal Unibody Design.\r\n', '648f0902eced5.jpg', '240.00', 'tablet'),
(97, 3, ' Samsung Galaxy Tab A8 10.5 inches Display, RAM 3 GB, ROM 32 GB Expandable, Wi-Fi Tablets, Gray, (SM-X200NZAAINU)', 'Samsung ', ' Display size - 26.69 cm (10.5 inch); Vibrant Display 1920x1200 (WUXGA) TFT, Aspect ratio 16:10. Symmetric Narrow Bezel.\r\nCalling supported -Wi-Fi calling; 3 GB RAM, 32 GB Internal Memory (expandable to 1 TB); Processor Description - UniSOC T618 (Dual 2.0GHz + Hexa 2.0GHz); Operating system - Android 11.0.\r\nBattery power - 7040 mAh Battery With 15W Fast Charging; Camera Front - 5.0MP, Camera Back - 8MP AF, Camera Flash - No.\r\nFinger print sensor - No; GPS - GPS + GLONASS, Beidou, Galileo ; Stylus compatible - S Pen not included; headphone jack - 3.5mm Stereo; Quad speakers with Dolby Atmos Speakers.\r\n', '648f095cad230.jpg', '220.00', 'tablet'),
(98, 3, 'Apple 2021 iPad Mini with A15 Bionic chip (Wi-Fi, 64GB) - Pink (6th Generation)', 'Apple ', '\r\n    21.08 cm (8.3-inch) Liquid Retina display with True Tone and wide colour.\r\n    A15 Bionic chip with Neural Engine.\r\n    Touch ID for secure authentication.\r\n    12MP Wide back camera, 12MP Ultra Wide front camera with Centre Stage.\r\n    Available in purple, starlight, pink and space grey.\r\n    Landscape stereo speakers.\r\n    Stay connected with ultra-fast Wi-Fi 6.\r\n\r\n    Up to 10 hours of battery life.\r\n    USB-C connector for charging and accessories.\r\n    Works with Apple Pencil (2nd generation).\r\n\r\n', '648f0a0e98d76.jpg', '250.00', 'tablet'),
(99, 3, 'HP All-in-One PC Intel Celeron J4025 21.5 inch(54.6cm) FHD Anti-Glare Display (8GB RAM/512GB SSD/Win 11/Intel UHD Graphics 600', 'HP', '\r\n    Processor:Intel Celeron J4025 (2.0 GHz base frequency(2b), up to 2.9 GHzup to 2.9 GHz, 2 4 MB L2 cache, 2cores, 2 threads).\r\n    Display & Graphics: 54.6 cm (21.5\") diagonal, FHD (1920 x 1080), VA, three-sided micro-edge, anti-glare, 250 nits, 72% NTSC.\r\n    Memory & Storage: 8 GB DDR4-3200 MHz RAM (1 x 8 GB)| 512 GB PCIe NVMe M.2 SSD|Expansion Slots: 2 M.2 (1 for SSD, 1 for WLAN).\r\n    Operating System & Software: Windows 11 Home 64 Plus Single Language| Microsoft Office Home & Student Edition 2021.\r\n    Other Feature: Graphics & Networking :Intel UHD Graphics 600| Networking :Realtek RTL8821CE-M 802.11a/b/g/n/ac (1x1) Wi-Fi and Bluetooth 4.2 combo Integrated 10/100/1000 GbE LAN|Audio: 2 Internal Speakers, Rear Headphone/MIC Combo Jack|Keyboard & Mouse: HP 310 White Wired Keyboard and mouse combo.\r\n', '648f0aff6a180.jpg', '500.00', 'computer'),
(100, 3, 'Lenovo IdeaCentre AIO 3 12th Gen Intel i5 27\" FHD IPS 3-Side Edgeless All-in-One Desktop with Alexa Built-in (16GB/512GB SSD/Win11/MS Office 2021)', 'Lenovo ', '\r\n    Processor: 12th Gen Intel Core i5-12450H | Speed: 2.0 GHz (Base) - 4.4 GHz (Max) | 8 Cores (4P + 4E) | 12 Threads | 12MB Cache.\r\n    OS: Pre-Loaded Windows 11 Home Single Language with Lifetime Validity.\r\n    OS: Pre-Loaded Windows 11 Home Single Language with Lifetime Validity\r\n    Memory: 16GB RAM DDR4-3200 (Max) || Storage: 512GB SSD || Graphics: Integrated Intel Iris Xe Graphics.\r\n    Display: 27-inch FHD (1920x1080) | Brightness: 250 nits | IPS Display | Anit glare.\r\n    Camera: IR || Audio: 2x 3W Stereo speakers | High Definition (HD) Audio.\r\n    Connectivity: Wi-Fi 6 (11ax, 2x2) | Bluetooth 5.1.\r\n\r\n    Ports: 1x HDMI 1.4 | 2x USB-A 2.0 | 2x USB-A 3.2 Gen 2 | 1x Ethernet (RJ-45).', '648f0d3e01c3d.jpg', '530.00', 'computer'),
(101, 3, 'Apple 2023 Mac Mini Desktop Computer M2 chip with 8‑core CPU and 10‑core GPU, 8GB Unified Memory, 512GB SSD Storage.', 'Apple ', '\r\n    M2 chip for exceptional speed and performance.\r\n    8-core CPU packs up to 18 per cent faster performance to fly through everyday tasks.\r\n    10-core GPU with up to 35 per cent faster performance for graphics-intensive apps and games.\r\n    16-core Neural Engine for advanced machine learning.\r\n    From 8GB up to 24GB of unified memory, so everything you do is fast and fluid.\r\n', '648f0dcb35b83.jpg', '300.00', 'computer'),
(102, 3, 'IdeaCentre AIO 3 12th Gen Intel i3 27\" FHD IPS 3-Side Edgeless All-in-One Desktop with Alexa Built-in (8GB/512GB SSD/Win11/MS Office 2021)', 'Lenovo ', '\r\n    Processor: 12th Gen Intel Core i3-1215U | Speed: 1.2 GHz (Base) - 4.4 GHz (Max) | 6 Cores (2 Performance + 4 Efficiency) | 8 Threads | 10MB Cache.\r\n    OS and Software: Windows 11 Home | Office Home and Student 2021 | Xbox GamePass Ultimate 3-month subscription*.\r\n    Memory and Storage: 8GB SO-DIMM DDR4-3200 RAM, expandable up to 16GB | Storage: 512GB SSD.\r\n    Graphics: Integrated Intel UHD Graphics.\r\n    Connectivity: Wi-Fi 6 (11ax | 2x2) | Bluetooth 5.1 || Audio Chip: High Definition (HD) Audio | Speakers: 2x 3W.\r\n    Ports: 1x HDMI 1.4 | 2x USB-A 2.0 | 2x USB-A 3.2 Gen 2 | 1x Ethernet (RJ-45)\r\n    In The Box: Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual.\r\n', '648f0eb1ee573.jpg', '520.00', 'computer'),
(103, 3, 'ASUS Vivo AiO V222, 4 core Intel Pentium Silver J5040, All-in-One Desktop (8GB/256GB SSD/Integrated Graphics/Windows 11', 'ASUS ', '\r\n    Processor: Intel Pentium Silver J5040 Processor 2GHz (4M Cache, up to 3.2GHz, 4 cores)\r\n    Memory: 4GB DDR4 SO-DIMM *2 with | Storage: 256GB M.2 SATA SSD\r\n    Graphics: Integrated Intel UHD Graphics 605\r\n    Display: 54.6 cm (21.5) , Full HD (1920 x 1080) 16:9, 250nits LED-Backlit LCD, IPS-level Panel, Anti-glare display, sRGB: 100%, Screen-to-body ratio: 87%\r\n    Operating System: Pre-loaded Windows 11 Home with lifetime validity.\r\n    Other: 720p HD camera | Wi-Fi 5 (802.11ac) (Dual band) 1*1 | Bluetooth 4.1 | 2 x 3  W Stereo Built-in speaker | Built-in array microphone.\r\n    Side I/O Ports: 1x Kensington lock | 1x 3.5mm combo audio jack | 1x USB 2.0 Type-A.\r\n\r\n    Rear I/O Ports : 1x DC-in | 1x RJ45 LAN jack for LAN insert | 1x HDMI 1.4 | 4x USB 3.2 Gen 1 Type-A.\r\n', '648f0f6b5d6e8.jpg', '530.00', 'computer'),
(104, 2, 'Dell Optiplex 19\" All-in-One Desktop Computer Set(Intel i5 3470/8 GB/1TB HDD /19\" HD ', 'Dell ', '\r\n    The Dell Optiplex All in one AIO Desktop Computer full set comes equipped with a 19\" HD screen giving you the ultimate experience with excellent performance and versatility. Its Powered by CPU with core intel i5 3rd gen processor 8 GB RAM and 1 TB HDD along with Windows 10 Pro and MS Office pre installed.\r\n    Box Contains web conferencing ready :19\" HD Monitor, CPU,HD webcam, KB+Mouse,Wifi, VGA Cables,Power Cables,Speakers.\r\n    Comes with a variety of ports for all possible needs, USB 2.0, USB 3.0, parallel, serial connectors, VGA, esata, display port, keyboard, mouse connector, PCI express X16.\r\n    Enjoy High End Business Class performance with Core I5 3470, upto 3.2 Ghz turbo boost, Quad Core power by Intel Turbo Boost Technology. It comes preinstalled with Windows 10 Pro and MS Office.\r\n    Hardware Interface: Usb3.0; Hardware Platform: Windows.\r\n', '648f0ffbbcb13.jpg', '500.00', 'computer'),
(105, 2, 'Lenovo Thinkcentre 17\" All-in-One Desktop Set (Intel C2D - Dual Core/4 GB/500 GB /17\" Monitor,KB', 'Lenovo ', '\r\n    Product Type - Cellular Phone.\r\n    Item Package Quantity - 1.\r\n    Ram Size - 8 Gb.\r\n    Stoarge - 128 Gb.\r\n', '648f1f5cccd78.jpg', '500.00', 'computer');

-- --------------------------------------------------------

--
-- Table structure for table `products_rating`
--

CREATE TABLE `products_rating` (
  `sno` int(10) NOT NULL,
  `p_id` int(10) NOT NULL,
  `p_name` varchar(255) NOT NULL,
  `user_id` int(10) NOT NULL,
  `rating` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `transactions`
--
-- Error reading structure for table rentalgoods.transactions: #1030 - Got error 194 &quot;Tablespace is missing for a table&quot; from storage engine InnoDB
-- Error reading data for table rentalgoods.transactions: #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;FROM `rentalgoods`.`transactions`&#039; at line 1

-- --------------------------------------------------------

--
-- Table structure for table `usersinfo`
--

CREATE TABLE `usersinfo` (
  `sno` int(8) NOT NULL,
  `user_name` varchar(20) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `date_of_birth` varchar(10) NOT NULL,
  `aadhar_card_no` int(15) NOT NULL,
  `address` varchar(255) NOT NULL,
  `city` varchar(20) NOT NULL,
  `country` varchar(20) NOT NULL,
  `postcode` int(10) NOT NULL,
  `mobile_no` bigint(15) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `usersinfo`
--

INSERT INTO `usersinfo` (`sno`, `user_name`, `gender`, `date_of_birth`, `aadhar_card_no`, `address`, `city`, `country`, `postcode`, `mobile_no`, `email`, `password`, `timestamp`) VALUES
(4, 'Mukesh Suthar', 'male', '07/02/2001', 0, '232-surbhi vihar society, oppo. to renuka bhavan, bombay market to punagam road', 'surat', 'india', 395010, 8160814990, 'immukeshsuthar8@gmail.com', '$2y$10$5mYBSxirTkQIvcJ5xkWygeTtAhnk7Ggp06jCnMgdrt5HtvR6vAJXm', '2023-04-30 21:25:53'),
(5, 'smit unagar', 'male', '07/02/2003', 0, 'khgiugi', 'kugogiu', 'ukgiug', 98956, 989461978, 'smit@gmail.com', '$2y$10$BJTynwLincXqe1I7DO/9JuQC2F9J5pXpI4/h9vqWQP5LtDbg0WBde', '2023-04-30 21:37:53'),
(10, 'ravi ', 'male', '10/01/2001', 0, 'kyfyfkykj', 'lgululglk', 'lguglkglu', 48468, 94631684, 'ravi@gmail.com', '$2y$10$WwxdQ.FYxhZw80TJwFLvQubX/Ja9781ka0j2gEwauUYX7RFddUc/.', '2023-04-30 22:19:38'),
(15, 'nikhil khairnar', 'male', '15/08/2002', 6153, '132, mahadev nagar', 'surat', 'india', 395010, 9531946949, 'nikhil123@gmail.com', '$2y$10$TLLZTTxCowTGXRIpFZ257u6YNY5D87QYtGj6OHZAqOXf1izIdP96m', '2023-06-03 10:14:58'),
(16, 'mukesh suthar', 'male', '02/08/2003', 5494, 'D-21, surbhi vihar society', 'Bardoli', 'india', 395010, 4970654494, 'mukesh@gmail.com', '$2y$10$CL.olxPA1Q8.Z6qaz.YRtu5V8vr10YIPhYYdugg7aaCEMTynDQFPi', '2023-06-26 17:04:34');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_user_info`
--
ALTER TABLE `admin_user_info`
  ADD PRIMARY KEY (`sno`);

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`sno.`);

--
-- Indexes for table `contactus`
--
ALTER TABLE `contactus`
  ADD PRIMARY KEY (`sno`);

--
-- Indexes for table `customers`
--
ALTER TABLE `customers`
  ADD PRIMARY KEY (`sno`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products_rating`
--
ALTER TABLE `products_rating`
  ADD PRIMARY KEY (`sno`);

--
-- Indexes for table `usersinfo`
--
ALTER TABLE `usersinfo`
  ADD PRIMARY KEY (`sno`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_user_info`
--
ALTER TABLE `admin_user_info`
  MODIFY `sno` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `sno.` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT for table `contactus`
--
ALTER TABLE `contactus`
  MODIFY `sno` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `customers`
--
ALTER TABLE `customers`
  MODIFY `sno` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=106;

--
-- AUTO_INCREMENT for table `products_rating`
--
ALTER TABLE `products_rating`
  MODIFY `sno` int(10) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `usersinfo`
--
ALTER TABLE `usersinfo`
  MODIFY `sno` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
